### ISSUE TITLE
folder with .torrent ?

### ISSUE THREAD

**Issue by polzy** [itsToggle/plex_debrid#100]
Thank you very much, 
I tried your script and it is impressive !

Is it possible to process a folder with .torrent ?
For example :
I add a movie on overseer, it is added on Radarr
Radarr search and retrieves the .torrent
Plex_debrid adds the movie in plex
In parallel, my torrent client downloads the movie

Thanks you

**Comment by itsToggle** [comment]
That could be possible, but you can achieve the same behavior by simply integrating overseerr into plex_debrid:
Once a new request is made on overseerr, plex_debrid will instantly add the best, cached release to your debrid service and refresh your plex library. At the same time, Sonarr will also see the new overseerr request and download the movie locally in the background.
This could be what you were looking for - have you tried this?

**Comment by itsToggle** [comment]
Your first rule will not work, as "!" is not a negating character in regex language.
If you want to prefer x265 over x264, check the readme again. There is an example for that exact scenario.

Your current sorting rules will first and foremost prefer "(multi|truefrench|french)" releases. If the best possible resolution of these french releases is 480p, plex_debrid will download a 480p release. Note that there might be higher quality french releases available, but they might not be cached on your debrid service. plex_debrid will prefer any cached release over any uncached release, as the purpose of this download automation is to instantly stream content.

If you only want to download 2160p or 1080p releases, you can do this by defining a "version". Head over to "/Settings/Scraper Settings/Multiple Versions" and add a version "(2160|1080)".

Currently there is a feature called "uncached releases" which allows you to disable the download of uncached releases. I will expand this feature, so users can choose to not prefer cached releases over uncached releases.

The sorting of releases will be made more user friendly in the future aswell, I've been working on it already.
