### ISSUE TITLE
Couple of questions

### ISSUE THREAD

**Issue by dvdgorila** [itsToggle/plex_debrid#101]
Hello itsToggle, 

First and foremost thank you for creating a great project. I have a few questions, 

Is it possible for to run the script without the need to choose from the menu? Specially selecting 1 to run the script. I couldnt find away to start a docker container and have the script autorun. Same as calling the script directly via python. 

If i wanted to only download 4k web-dls what do i need to add to scraper? 4K HDR would be ideal,  I want to exclude anything less than 4k. (using real-debrid) I tried tinkering with with the sorting and got an error that there was something wrong. 

I tried using your version of rclone on both linux and macos and get a fuse error. Not sure why, but using webdav works fine for now. 

It would be nice to have an all in one container with your version of rclone and autostart  plex_rd.py. Im running Unraid so im going to look into this when I have some extra time.

**Comment by itsToggle** [comment]
Hey, yes its possible to run the script directly by disabling the setting "/Settings/UI Settings/show menu on startup" :)

You can define your resolution *preference* by sorting the scraped releases by completely costomizable rules, as detailed in the readme. If your sorting rules are set to prefer 2160p releases, and there are no 2160p releases for a particular movie, Plex_debrid will download lowering resolution releases. 

To actually exclude *anything* other than 2160p releases, and download nothing if no 2160p version is available, you can use the setting "/Settings/Scraper Settings/Multiple versions". Add one version rule for "(2160p)". To prefer HDR releases, add a preference for HDR content in your sorting rules (see the readme for examples).

Could you tell me the exact fuse error? 

An all in one container would be awesome,  but I have no idea how to add plex and all its dependencies to a docker container. I think my rclone fork and plex would need to be in the same container - Plex_debrid communicates entirely over http, so Plex_debrid could stay as a separate one.
