### ISSUE TITLE
Unable to find plex token

### ISSUE THREAD

**Issue by AsirShahid** [itsToggle/plex_debrid#105]
When I go to plex.tv/devices.xml, I just get to a page saying "Please sign in" instead of a token. However, if I just go to plex.tv, I can see that I am already signed in. I tried this on multiple computers and browsers.

Is there any other way to get the required token?

**Comment by itsToggle** [comment]
There are numerous ways to find your Plex token, a quick google search will lead you to this article from Plex :) https://support.plex.tv/articles/204059436-finding-an-authentication-token-x-plex-token/
