### ISSUE TITLE
{Optional}{Feature Request} Auto-deletion of movies and episodes after specified time

### ISSUE THREAD

**Issue by dspdhckr** [itsToggle/plex_debrid#106]
Hi there,
I am not sure how many people actually requires this but as of now after using you script for more than a three weeks, I just expanded my library by more than 34TB but the only issue is that if by any chance the played episodes and movies gets deleted lets say after 1 day, 1 week or 1 month automatically after setting up settings likewise would be great. This way the overhead of keeping track of vast library can be eliminated by the server as well as I as a user can see content seamlessly. This is a feature request and this can by default will be disabled to everyone to avoid any unwanted behaviour for majority of the people

**Comment by itsToggle** [comment]
Sounds like a cool idea! I'll add this in the coming weeks. There are a few existing scripts for something like this already (PlexCleaner and Cleanarr) but they seem outdated :)

**Comment by itsToggle** [comment]
You are right, when you have a large library like yours the script will constantly refresh your unrestricted links - sadly, that's a limitation on realdebrids part: 
They only allow us to fetch 100 links per request, so to check all your ~10.000 links, plex_debrid will need to make 100 requests to the realdebrid API which will definitely take a few seconds. Luckily I've written my rclone for so this is only done if the total number of torrents changes (like when you add a new torrent). This sadly can't be avoided. I'll check if there is anything else I can improve, waiting 5 minutes for an episode to start is definitely way too long.

I'm currently on holidays, but I'll add the auto delete feature and (hopefully) some rclone improvements in a week or two :)

**Comment by dspdhckr** [comment]
Yes, now to avoid congestion I have removed all public trakt list and most probably will reduce the content library in coming days. But yes auto deletion would help auto-arrange the library and size of it. Please do enjoy your holidays as to achieve ideal media system there is a long way ahead! But for sure we will achieve it.

**Comment by itsToggle** [comment]
Hey, this isn't an update on progress or anything, I just had a thought about your library size which I wanted to share:
Since plex_debrid can download movies and shows almost instantaniously, why pre-download so much stuff? You can simply browse the discover part of plex (or trakt) and watch anything that sounds interesting right away. It's much easier to maintain a library that really only contains things you or your home users want to watch :)
Just an idea, I will still add the auto delete feature :)

**Comment by dspdhckr** [comment]
Hey you know what? This do make more sense. I should treat it as VOD service. But yes that is also true that more we use this service more content will be accumulated over time and this auto deletion feature will save future scenarios of library crossing said limits. I do appreciate your thought and from now on I will ask my home users to put only shows they are intended to watch in coming days or the movies for that matter. This give me one additional thought of auto-deletion, if we can have flexible rules just like scraping one as,

1. Delete a file created before n number of days
2. Delete a file after marked as watched after n number of days and

This will give us more granular control over the deletion process and people can avoid larger libraries created over time as more and more data, movies and shows will be collected.

**Comment by TheSpeedHacker** [comment]
Hey there adding the additional observation which I am experiencing right now. So if we add any TV show to the watchlist and if that TV show does have many other similar named TV shows or movies available then the script will fetch that content  as well. Meanwhile user will only watch the required content he wished for and will ignore the other files. In this case, if list auto removal is only turned on for movies and not TV shows, meaning after successful content fetch if script is only deleting Movies from the list and not TV shows then the script will again add up the rest, similar named shows again when user deletes them. Meanwhile, the user who was interested to watch series A had his series watched completely and now he wishes to delete series A along with Series B,C,D and F which are almost identical to the series A name, then the script will scrape the sources again and this way user will keep seeing the similarly named show even after deleting unwatched similar named shows. Bit confusing but let me know whether you understood this or not? I can then try better explaining it.

**Comment by itsToggle** [comment]
Hey, sorry for the late response. The behavior of downloading similary titled tv shows is now dealt with.

**Comment by itsToggle** [comment]
Hi, autodeletion can be integrated with rclone filtering! No need to actually write any sort of script for this. Check out https://rclone.org/filtering/ for some more information on filtering your remote :) You will need rclone_rd for this to work, since the webdav can't delete torrents.

You could for example add the tag "--max-age 30d" (which will exclude any files older than 30 days). If you then add the tag "--delete-excluded", any torrents older than this will be deleted :)

**Comment by dspdhckr** [comment]
This does work with your rclone version, right?

**Comment by itsToggle** [comment]
Yes, any command that works with the official rclone version also works with my fork :)

**Comment by dspdhckr** [comment]
That is great!! Thanks, and I will do it.
