### ISSUE TITLE
{Option Request} Disable refresh after successfully fetching the content

### ISSUE THREAD

**Issue by dspdhckr** [itsToggle/plex_debrid#107]
Hey there,

Is there any way I can disable auto refresh after successful content fetch? I have disabled auto-refresh when directory changes are detected but have enabled 'Only scan changes' option. The reason why would I want to to do it is because of my library size. It is whopping 34TB and may expand further in future as I am fetching data from various public Trakt list.

**Comment by itsToggle** [comment]
Hey, I could implement a feature where only the newly added torrent is scanned. This can't be done via the plex http api, but can be done through plex terminal commands.

**Comment by dspdhckr** [comment]
If this can be implemented then if I may recommend the approach should consider two things,

1. Only the timestamp from which the search started should be considered for file creation times
2. Refresh should only occur when the entire process is over. I mean after fetching a show or movie, the script is refreshing the library but ideally it should consider batch processing. Once the batch fetching is over then only the refresh should happen.

**Comment by themegaphoenix** [comment]
> If this can be implemented then if I may recommend the approach should consider two things,
> 
> 1. Only the timestamp from which the search started should be considered for file creation times. Splitting of drive or something like that where only the portion of the disk to be scanned which was created or modified after fetching operation started.
> 2. Refresh should only occur when the entire process is over. I mean after fetching a show or movie, the script is refreshing the library but ideally it should consider batch processing. Once the batch fetching is over then only the refresh should happen.

A simpler way would be to send a webhook to AutoScan and let Autoscan handle the refresh:
https://github.com/Cloudbox/autoscan

With Sonarr and Radarr it send a webhook to Autoscan, and Autoscan then tell Plex to scan that specific directory.

**Comment by themegaphoenix** [comment]
> > If this can be implemented then if I may recommend the approach should consider two things,
> > 
> > 1. Only the timestamp from which the search started should be considered for file creation times. Splitting of drive or something like that where only the portion of the disk to be scanned which was created or modified after fetching operation started.
> > 2. Refresh should only occur when the entire process is over. I mean after fetching a show or movie, the script is refreshing the library but ideally it should consider batch processing. Once the batch fetching is over then only the refresh should happen.
> 
> A simpler way would be to send a webhook to AutoScan and let Autoscan handle the refresh: https://github.com/Cloudbox/autoscan
> 
> With Sonarr and Radarr it send a webhook to Autoscan, and Autoscan then tell Plex to scan that specific directory.

this would also solve #65

**Comment by itsToggle** [comment]
That's a cool project! This would take writing the terminal commands for different operating systems off my hands (stated as a problem in an earlier response).

**Comment by itsToggle** [comment]
I will close this issue and start a new one regarding the implementation of partial library scans.
