### ISSUE TITLE
Automatically scrapes for TV shows, but not movies

### ISSUE THREAD

**Issue by Xenon1** [itsToggle/plex_debrid#110]
Hey,

Amazing script and is the perfect answer to my niche streaming solution wants, however i am having a slight issue.

When adding a TV show to my plex watchlist, it instantly scrapped and automatically updated my plex library as intended. However, this is not the case for movies. Tested with 2 movies, the script recognises the movies are added to the watchlist, but does not start to scrape for them, See attached image
![image](https://user-images.githubusercontent.com/28608526/189350515-2353928a-6e2a-4d84-9b59-1d117ce82976.png)

However, if i exit out and manually search for the movies with the scrapper (pressing 4), it finds all releases, downloads whatever is selected and is added to the plex library. Not sure what the issue could be, and it's not the end of the world but doesn't seem intended

**Comment by Xenon1** [comment]
Instant update does not seem to be every movie. See here it automatically scrapped for 1 movie, but not another movie 
![image](https://user-images.githubusercontent.com/28608526/189352058-36344d71-b2e8-4cf9-b05f-6df87041b2bf.png)

**Comment by Xenon1** [comment]
I have discovered i am a moron. What was happening is i add it to my watch list then marked it as played before letting it be scrapped, this of course stops it being downloaded. Nothing wrong with the script

**Comment by itsToggle** [comment]
Haha :D I was wondering what could cause this behavior! Good thing you found the issue :)
