### ISSUE TITLE
Trakt Problem?

### ISSUE THREAD

**Issue by Dexxa1024** [itsToggle/plex_debrid#12]
Just downloaded the new one and i added my Trakt username and did the auth code but its coming up with errors 
![error](https://user-images.githubusercontent.com/11196220/171747000-68e032a7-3471-4011-92ce-12bd493e6d18.png)

The scripts great, I've used it a lot, Think i've tired it out lol

**Comment by itsToggle** [comment]
As sorry I didnt acutally try that part out after I did some changes. It should be fixed now :)
