### ISSUE TITLE
Navigate the Settings

### ISSUE THREAD

**Issue by sasagr** [itsToggle/plex_debrid#125]
Hi. I have difficulties to understand how to navigate the settings. For example in the readme you describe to go for example to 
“/Settings/Scraper Settings/Multiple Versions/Edit”
The only way I understood I can enter the script setup, within the docker, is with the command “ docker run -ti plex_debrid” that always force me to start from the initial setup.

**Comment by sasagr** [comment]
I think my issue is that the script does not save the initial settings so every time I launch "docker run -ti plex_debrid" I get the 
           __                  __     __         _     __
    ____  / /__  _  __    ____/ /__  / /_  _____(_)___/ /
   / __ \/ / _ \| |/_/   / __  / _ \/ __ \/ ___/ / __  / 
  / /_/ / /  __/>  <    / /_/ /  __/ /_/ / /  / / /_/ /  
 / .___/_/\___/_/|_|____\__,_/\___/_.___/_/  /_/\__,_/   
/_/               /_____/                                

Initial Setup

Press Enter to continue:

**Comment by sasagr** [comment]
tried the Standard installation and it worked fine. So the issue is with the docker installation. Mu machine is a raspberry pi with debian

**Comment by itsToggle** [comment]
Ive only tried the docker version on docker desktop for windows, which worked for me - I sadly can't test any further than that. Glad it's working with the standard version, I'll see if I can do anything about the docker.
