### ISSUE TITLE
Jackett as an indexer/scraper

### ISSUE THREAD

**Issue by morpheasgr** [itsToggle/plex_debrid#13]
https://github.com/Murmiration/plex_rd-jackett

Have you seen this fork of your project? You seem to have interacted with the dev at some point. I am experimenting with Jackett right now too in some way, managed to get an instance of it running remotely on a Heroku dyno and I'm trying to integrate its API to control my debrid services, instead of having to use the arr apps (Sonarr, Radarr etc) which require downloading content/hoarding and running everything 24/7 on a home server.

**Comment by itsToggle** [comment]
Damn I should pay more attention to the forks! Ive implemented jackett yesterday or the day before, I had no idea there was already an existing implementation out there. Luckily @Murmiration is already a contributer. So yeah, jackett is awesome and Ive already implemented it :) Im still working on some of the settings, but you can already enter your API Key and the Jackett URL via the UI and scrape all your Jackett indexers. In the Future youll be able to specify categories and select which indexers you want to use.
