### ISSUE TITLE
docker container not saving settings

### ISSUE THREAD

**Issue by Gaisberg** [itsToggle/plex_debrid#138]
Would it be possible to save settings in a config file f/e if instance is restarted?

**Comment by itsToggle** [comment]
plex_debrid should create a settings.json file after you've configured it once. Are you running the dockerized version? Other people who are using the docker version are reporting that the file does not get saved anywhere. I'm currently researching on why that would be.

**Comment by Gaisberg** [comment]
Yeah I am on linux. Possibly because we arent mounting a volume for configuration?

**Comment by itsToggle** [comment]
Oh nice! Any idea on how I could implement that in the dockerfile of this repository? Or will I need to actually build the docker container and share that?

**Comment by Gaisberg** [comment]
1. Modify the code to use ./config/settings.json
2. Start container with `'docker run -ti plex_debrid -v /path/on/host:/config --restart unless-stopped'`

**Comment by itsToggle** [comment]
Solved and implemented with latest commit

**Comment by jferris-** [comment]
> Solved and implemented with latest commit

This is not solved :(

The config folder is empty.
Used: -v /mnt/user/appdata/plex_debrid:/config

**Comment by itsToggle** [comment]
works for everyone else, so it must be something on your end

**Comment by itsToggle** [comment]
whats the complete run command?

**Comment by jferris-** [comment]
> whats the complete run command?

docker run
  -d
  --name='plex_debrid'
  --net='bridge'
  --privileged=true
  -e TZ="Europe/London"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="box"
  -e HOST_CONTAINERNAME="plex_debrid"
  -l net.unraid.docker.managed=dockerman
  -v '/mnt/user/appdata/plex_debrid':'/config':'rw'
  -ti
  --restart unless-stopped 'itstoggle/plex_debrid'

**Comment by jferris-** [comment]
> whats the complete run command?

Found the issue. Configs aren't being saved to the /config directory. They're saving to root.
![image](https://user-images.githubusercontent.com/7659646/220190692-5da67db6-1515-4282-ab92-54dccee2b5b4.png)

**Comment by itsToggle** [comment]
yes. for compatability to older versions, plex_debrid first looks for a settings.json file in the root directory. If there is no such file, it will try to use the directory passed to "main.py" using the "--config-dir" flag. 

If you run the docker image from dockerhub directly, this "--config-dir" flag is set to "config". I dont know why it wouldnt be in your case.

**Comment by jferris-** [comment]
> yes. for compatability to older versions, plex_debrid first looks for a settings.json file in the root directory. If there is no such file, it will try to use the directory passed to "main.py" using the "--config-dir" flag.
> 
> If you run the docker image from dockerhub directly, this "--config-dir" flag is set to "config". I dont know why it wouldnt be in your case.

Is there a way I can use an extra parameter to get around this for the time being, until it's patched, please?

**Comment by itsToggle** [comment]
There is nothing to be patched. This works.

**Comment by jferris-** [comment]
> There is nothing to be patched. This works.

Ran from fresh.
Setup with 'python ./main.py --config-dir config'.
settings.json was saved to /config.
After reboot or the container, it would instantly crash and power off.

`Traceback (most recent call last):
  File "//./main.py", line 21, in <module>
    ui.run(config_dir, service_mode)
  File "/ui/__init__.py", line 344, in run
    if setup():
       ^^^^^^^
  File "/ui/__init__.py", line 245, in setup
    settings = json.loads(f.read())
               ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 248 column 5 (char 5056)
Traceback (most recent call last):
  File "//./main.py", line 21, in <module>
    ui.run(config_dir, service_mode)
  File "/ui/__init__.py", line 344, in run
    if setup():
       ^^^^^^^
  File "/ui/__init__.py", line 245, in setup
    settings = json.loads(f.read())
               ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 248 column 5 (char 5056)`

**Comment by itsToggle** [comment]
That sounds like edited the settings.json file manually and broke the json formatting, or the json file is broken for some other reason. I have no idea what you are doing. Perhaps join the discord server and ask for some docker pointers over there?

**Comment by jferris-** [comment]
> That sounds like edited the settings.json file manually and broke the json formatting, or the json file is broken for some other reason. I have no idea what you are doing. Perhaps join the discord server and ask for some docker pointers over there?

Thank you. Was indeed a mistake I made when editing the .JSON.

So looks like the issue is the Docker version is writing to **/** over **/config**. Resolved by setting up with **python ./main.py --config-dir config**.

Thank you so much for this project and your work put into it!
