### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by sasagr** [itsToggle/plex_debrid#142]
I was testing the scraper and I got this error. Not sure if it something I can fix on my side of it needs a fix in the script.

Enter a query: the.princess.bride.1987

[2022-09-23 11:21:13.661181] scraping sources for query "the.princess.bride.1987" ... done - found 48 releases

0) Back
1)  title: The.Princess.Bride.1987.2160p.BluRay.HDR.DTS-HD.MA.5.1.HEVC-DDR.mkv            | size: 13.01 | cached: RD | seeders: 3   | files: +1/-0 | source: [jackett: TorrentGalaxy]
2)  title: The.Princess.Bride.1987.BDRip.2160p.UHD.HDR10Plus.Eng.DTS-HD.MA.DD5.1.gerald99 | size: 18.37 | cached: RD | seeders: 3   | files: +1/-0 | source: [jackett: TorrentGalaxy]
3)  title: The.Princess.Bride.1987.BDRip.2160p.UHD.HDR10Plus                              | size: 18.37 | cached: RD | seeders: 0   | files: +1/-0 | source: [jackett: The Pirate Bay]
4)  title: The.Princess.Bride.1987.REMASTERED.1080p.BluRay.H264.AAC-RARBG                 | size: 2.03  | cached: RD | seeders: 107 | files: +5/-0 | source: [rarbg]
5)  title: The.Princess.Bride.1987.REMASTERED.1080p.BluRay.H264.AAC-RARBG                 | size: 2.03  | cached: RD | seeders: 107 | files: +5/-0 | source: [jackett: RARBG]
6)  title: The.Princess.Bride.1987.REMASTERED.1080p.BluRay.H264.AAC                       | size: 2.03  | cached: RD | seeders: 88  | files: +5/-0 | source: [jackett: The Pirate Bay]
7)  title: The.Princess.Bride.1987.REMASTERED.1080p.BluRay.H264.AAC                       | size: 1.9   | cached: RD | seeders: 18  | files: +5/-0 | source: [1337x]
8)  title: The.Princess.Bride.1987.REMASTERED.1080p.BluRay.x265-RARBG                     | size: 1.65  | cached: RD | seeders: 37  | files: +2/-0 | source: [jackett: RARBG]
9)  title: The.Princess.Bride.1987.1080p.BluRay.DTS.x264-LoNeWoLf                         | size: 8.0   | cached: RD | seeders: 44  | files: +1/-0 | source: [1337x]
10) title: The.Princess.Bride.1987.1080p.bdrip.x265.5.1.AAC-FINKLEROY                     | size: 7.1   | cached: RD | seeders: 24  | files: +1/-0 | source: [1337x]
11) title: The.Princess.Bride.1987.REMASTERED.1080p.BluRay.x264.DTS-HD.MA.5.1-FGT         | size: 12.29 | cached: RD | seeders: 8   | files: +1/-0 | source: [rarbg]
12) title: The.Princess.Bride.1987.REMASTERED.1080p.BluRay.x264.DTS-HD.MA.5.1-FGT         | size: 12.29 | cached: RD | seeders: 8   | files: +1/-0 | source: [jackett: RARBG]
13) title: The.Princess.Bride.1987.1080p.Bluray.DTS.x264-LoNeWoLf                         | size: 8.55  | cached: RD | seeders: 6   | files: +1/-0 | source: [jackett: The Pirate Bay]
14) title: The.Princess.Bride.1987.REMASTERED.1080p.BluRay.X264-AMIABLE                   | size: 10.57 | cached: RD | seeders: 4   | files: +1/-0 | source: [rarbg]
15) title: The.Princess.Bride.1987.REMASTERED.1080p.BluRay.X264-AMIABLE                   | size: 10.57 | cached: RD | seeders: 4   | files: +1/-0 | source: [jackett: RARBG]
16) title: The.Princess.Bride.1987.1080p.BluRay.x264.DTS-FHD                              | size: 7.42  | cached: RD | seeders: 4   | files: +1/-0 | source: [rarbg]
17) title: The.Princess.Bride.1987.1080p.BluRay.x264.DTS-FHD                              | size: 7.42  | cached: RD | seeders: 4   | files: +1/-0 | source: [jackett: RARBG]
18) title: The.Princess.Bride.1987.1080p.bdrip.x265.5.1.AAC-FINKLEROY                     | size: 7.59  | cached: RD | seeders: 1   | files: +1/-0 | source: [jackett: The Pirate Bay]
19) title: The.Princess.Bride.1987.1080p.BluRay.x264.anoXmous                             | size: 1.72  | cached: RD | seeders: 1   | files: +1/-0 | source: [jackett: The Pirate Bay]
20) title: The.Princess.Bride.1987.1080p.BluRay.H264.AAC-RARBG                            | size: 2.01  | cached: RD | seeders: 1   | files: +1/-0 | source: [rarbg]
21) title: The.Princess.Bride.1987.1080p.BluRay.H264.AAC-RARBG                            | size: 2.01  | cached: RD | seeders: 1   | files: +1/-0 | source: [jackett: RARBG]
22) title: The.Princess.Bride.1987.(1080p.x265.HEVC.AAC.5.1.Joy)                          | size: 0.81  | cached: RD | seeders: 0   | files: +1/-0 | source: [jackett: The Pirate Bay]
23) title: The.Princess.Bride.1987.{1080p}{5.1}{DTS.MA}{PcTechPaul}                       | size: 1.95  | cached:    | seeders: 0   | files: +0/-0 | source: [jackett: The Pirate Bay]
24) title: The.Princess.Bride.1987.1080p.BluRay.x264.DTS-FGT                              | size: 14.92 | cached:    | seeders: 0   | files: +0/-0 | source: [rarbg]
25) title: The.Princess.Bride.1987.1080p.BluRay.x264.DTS-FGT                              | size: 14.92 | cached:    | seeders: 0   | files: +0/-0 | source: [jackett: RARBG]
26) title: The.Princess.Bride.1987.US.BluRay.1080p.DTS.dxva-LoNeWolf                      | size: 15.11 | cached:    | seeders: 0   | files: +0/-0 | source: [jackett: The Pirate Bay]
27) title: The.Princess.Bride.1987.720p.BRRip.x264.YIFY                                   | size: 0.9   | cached: RD | seeders: 88  | files: +1/-0 | source: [1337x]
Traceback (most recent call last):
  File "plex_rd.py", line 3807, in <module>
    ui.run()
  File "plex_rd.py", line 3785, in run
    ui.options()
  File "plex_rd.py", line 3715, in options
    ui.options()
  File "plex_rd.py", line 3715, in options
    ui.options()
  File "plex_rd.py", line 3714, in options
    option.input()
  File "plex_rd.py", line 3170, in input
    func()
  File "plex_rd.py", line 3603, in scrape
    releases.print(scraped_releases)
  File "plex_rd.py", line 2727, in print
    print(str(index+1)+") "+' ' * (longest_index-len(str(index+1)))+"title: " + release.title + ' ' * (longest_title-len(release.title)) + " | size: " + str(release.printsize) + ' ' * (longest_size-len(str(release.printsize))) + " | cached: " + '/'.join(release.cached) + ' ' * (longest_cached-len('/'.join(release.cached))) + " | seeders: " + str(release.seeders) + ' ' * (longest_seeders-len(str(release.seeders))) + " | files: " + release.file + ' ' * (longest_file-len(release.file)) + " | source: " + release.source )
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2b50' in position 87: ordinal not in range(256)

**Comment by itsToggle** [comment]
[issue and solution discussed on discord]

Will be implemented in next commit
