### ISSUE TITLE
(solved) No Releases are addes since newest update

### ISSUE THREAD

**Issue by piratsch** [itsToggle/plex_debrid#15]
Hi :)

Ever since I updated to the newest version, no releases are added (even when many are found).
Release sorting settings:

```
"Release sorting":[
            [
                "(1080|720|480)(?=p|i)",
                "title",
                "number",
                "1"
            ],
            [
                "(.*)",
                "wanted",
                "number",
                "1"
            ],
            [
                "(.*)",
                "unwanted",
                "number",
                "0"
            ],
            [
                "(1337x)",
                "source",
                "text",
                "0"
            ],
            [
                "(EXTENDED|REMASTERED)",
                "title",
                "text",
                "1"
            ],
            [
                "(h.?265|x.?265)",
                "title",
                "text",
                "1"
            ],
            [
                "(.*)",
                "title_deviation",
                "number",
                "0"
            ],
            [
                "(.*)",
                "size",
                "number",
                "0"
            ]
        ]
```

Any Ideas on what's going on here?

**Comment by itsToggle** [comment]
Which debrid service/s have you set up? Does it work, If you try the new version with the old 'Release sorting' settings? You could rename the settings backup (old.json) to 'settings.json' and try it again

**Comment by piratsch** [comment]
The Problem was that I didn't have any debrid services set up (`"Debrid Services": [],`) was empty.
Thanks!

**Comment by itsToggle** [comment]
Ah okay. Was that a change you made or was it something that the update caused?

**Comment by piratsch** [comment]
The update didn't populate the list. I'm usually not running the scrip "interactive" though. So for people like me, a documentation of the possible settings entries would be best!

**Comment by itsToggle** [comment]
>  So for people like me, a documentation of the possible settings entries would be best!

Check out this wiki page, let me know if you want me to go into depth a bit more: https://github.com/itsToggle/plex_debrid/wiki/all-json-settings

**Comment by itsToggle** [comment]
added preflight checks that will tell the user if a crucial setting is missing. This issue can be unpinned.
