### ISSUE TITLE
Integrate a4kscrapers as some more "legacy" scrapers

### ISSUE THREAD

**Issue by itsToggle** [itsToggle/plex_debrid#152]
Some of you can't really use Jackett or prowlarr because of your ISP and would like to use the a4kscrapers and their always-up-to-date list of proxies, so I will try to implement the a4kscrapers aside my own scrapers for rarbg and 1337x.

**Comment by dvdgorila** [comment]
+1 

Can you also consider implementing orionoid? It works really well with debrid

**Comment by itsToggle** [comment]
> +1
> 
> Can you also consider implementing orionoid? It works really well with debrid

orionoid has been integrated.

Im struggeling a little more with a4kscrapers, as they are specifically taylored for a trakt integration. Im going to have to write the scrapers myself and only rely loosely on their always-up-to-date list of proxies.

**Comment by dvdgorila** [comment]
thanks itsToggle, I've tested it, no issues so far

**Comment by dreulavelle** [comment]
I was gonna suggest this too. Although I think that Prowlarr should integrate a4kScrapers into theirs, making Prowlarr the End-All-Be-All to scraping.

**Comment by itsToggle** [comment]
this will likely not ever happen, as the a4kscrapers are running on a trakt implementation. I cant really use their code, I could at best use their proxy list - which is not much of a benefit. I will close this issue as I dont see this happening. If anyone else wants attempt an integration, feel free.
