### ISSUE TITLE
when monitoring the trakt collection, new episodes are not downloaded on time.

### ISSUE THREAD

**Issue by itsToggle** [itsToggle/plex_debrid#154]

**Comment by itsToggle** [comment]
the only difference between how plex_debrid monitors your trakt watchlist and your trakt collection is the following:

Large amounts of data need to be collected in order to determine if a shows new episode needs to be downloaded. Plex_debrid loads all this data for the shows in your watchlist without hesitation, but doesn't for your trakt collection, since that would entail getting all this data for every show you've ever collected. Instead, it first checks the shows in your collection for the "aired_episodes" attribute (number of aired episodes) and compares this to the amount of episodes that are marked as "collected". If there are more episodes aired than you have collected, plex_debrid will gather all the data needed to determine if the uncollected episodes need to be downloaded.

It seems that Trakt is slow in updating this "aired_episodes" attribute. 

I didn't know this was an issue, so I will change how collected shows can be checked in a data-saving way. Besides, I now realize that your trakt collection might not be kept up-to-date, since plex_debrid doesn't currently allow you to maintain both your Plex and your Trakt library. This means that the number of collected episodes might be different from the aired episodes for numerous shows, which would make this entire check redundant.

**Comment by joshali1990** [comment]
Not sure if this would work for everyone, but since I want my trakt collection to be the same as my Plex library I just deleted the aired_episodes check. The Plex library check confirms if the item is already in my library and downloads if not. Doesn't seem to slow down the check too much.

**Comment by itsToggle** [comment]
Do you mind me asking how many shows and movies you have in your collection? If it truly doesn't slow down the check that's done every 30 mins too much, I could simply remove it as well.

**Comment by joshali1990** [comment]
150+

**Comment by itsToggle** [comment]
Okay thats a usual amount i think, i have about the same number :) It does mean that plex_debrid will make 150 calls (or how ever many items in the collection) to the trakt API every thirty minutes, but that should never hit the 1000 get calls per 5 minutes limit. Alright, Ill delete the "aired episodes" check in the next commit.
