### ISSUE TITLE
Search by show aliases

### ISSUE THREAD

**Issue by joshali1990** [itsToggle/plex_debrid#157]
Can you add a a step to search by trakt show aliases if nothing is found? I ask because the show ghosts scrapes for ghosts.us, but tracker results are only found by searching for ghosts.2021.

**Comment by itsToggle** [comment]
Nice idea, I've implemented this in past projects and it works great! For now, you could create a character replacement rule to replace "ghosts.us" with "ghosts.2021". You can find the character replacement in the scraper settings I think.

**Comment by joshali1990** [comment]
Will do thanks!

**Comment by itsToggle** [comment]
implemented in experimental brach v2.29
