### ISSUE TITLE
rclone cache issues 

### ISSUE THREAD

**Issue by Kabyss** [itsToggle/plex_debrid#158]
After mounting real debrid using your rclone fork and playing any particular media file from Plex, the entire real debrid library gets cached and fills up the disk. Is this intended or can we just cache only the file that is currently being played?

**Comment by itsToggle** [comment]
Yes this is somewhat intended, you can limit the amount rclone is allowed to cache by adding the tag "--vfs-max-cache-size 10G" (this limits it to 10GB). I should make that clearer in the readme!
