### ISSUE TITLE
Feature request: ability to add magnets manually 

### ISSUE THREAD

**Issue by krishne35** [itsToggle/plex_debrid#166]
Thank you for your great work 

I have hosted ur script on a remote server since Rd is very specific with ip address is it possible to give option to add magnets manually for regional content which aren't available on global indexers 

Thank you :)

**Comment by itsToggle** [comment]
You can scrape for releases manually from the main menu scraper. Adding magnet links manually is not a feature yet, as you can simply use the realdebrid website to add your torrents manually. If you refresh your library afterwards, rclone_rd will unrestrict the torrents files. You can add torrents to realdebrid from anywhere. The IP that unrestricts the files is the one that should remain the same. Though even having multiple IP adresses unrestrict your files is not a banable offense - You simply won't be able to open files which have been unrestricted from a different IP address. The only thing that will actually give you account sharing notices and ultimately a ban is if you are simultaneously downloading files from multiple locations at the same time.

Regarding region specific content, have you considered integrating Jackett into plex_debrid to add some region-specific indexers? 🙂

**Comment by krishne35** [comment]
Thanks for the reply 
Regarding refresh library u mean from plex? 
Coz I'm using jellyfin and it didn't unrestrict them again 😐

Sadly my regional stuff torrents don't have indexers ;-; 

But I didn't find a cool script to do so 

For anyone who need it [REDDIT](https://www.reddit.com/r/Addons4Kodi/comments/jpgao0/rdtoolsh_a_bash_script_to_managing_realdebrid/)

**Comment by itsToggle** [comment]
Answered on discord
