### ISSUE TITLE
Issue with current script version

### ISSUE THREAD

**Issue by dspdhckr** [itsToggle/plex_debrid#171]
Hi there,

Whenever I am trying to run the newest version of the script on my machine, the following error is coming up,

    Exception in thread Thread-1 (run):
    Traceback (most recent call last):
    File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
    File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
    File "/scripts/plex_rd.py", line 3389, in run
    element.download(library=library)
    File "/scripts/plex_rd.py", line 462, in download
    debrid_downloaded, retry = self.debrid_download()
    File "/scripts/plex_rd.py", line 638, in debrid_download
    releases.sort(self.Releases,self.version)
    File "/scripts/plex_rd.py", line 2889, in __new__
    scraped_releases = rule.apply(scraped_releases)
    File "/scripts/plex_rd.py", line 2738, in apply
    if bool(regex.search(self.value,getattr(release,self.attribute),regex.I)):
    File "/usr/local/lib/python3.10/dist-packages/regex/regex.py", line 267, in search
    pat = _compile(pattern, flags, ignore_unused, kwargs, True)
    File "/usr/local/lib/python3.10/dist-packages/regex/regex.py", line 546, in _compile
    raise error(caught_exception.msg, caught_exception.pattern,
    regex._regex_core.error: missing ) at position 9

Please help.

**Comment by itsToggle** [comment]
Hi, did you edit the new versions setting? The error is telling you that there is a "(" missing at position "9" of one of your version rules. I have not yet implemented a check for the values you guys enter, I should definitly do that.

**Comment by dspdhckr** [comment]
I have this setting for 1080p version set.. this is the only rule I have right now...

`Options/Settings/Scraper Settings/Versions/Edit


Current settigns for version [1080P SDR]:

0) Back
1) cache status  requirement :  uncached  
2) resolution    requirement :        <=  1080
3) resolution    preference  :   highest  
4) title         requirement :   exclude  (\.DV\.|3D|\.H?D?.?CAM\.)
5) title         requirement :   exclude  (\.HDR.\)
6) title         preference  :   include  (EXTENDED|REMASTERED)
7) size          preference  :    lowest  
8) seeders       preference  :   highest  
9) size          requirement :        >=  0.5

Choose a rule to edit or add a new rule by typing 'add'
To rename this version, type 'rename'
To delete this version, type 'remove'

Choose an action: 
`

**Comment by itsToggle** [comment]
could you change the "cache status" to "cached"? Or why would you require the releases to be downloaded to be uncached?

**Comment by dspdhckr** [comment]
Okay this morning I was not able to see the latest episode of H.o.t.d. so thought that this setting was not fetching the latest episode. Is it okay to keep only this version rule or do I need to add more so I can see latest episodes properly without interference from my end.

**Comment by itsToggle** [comment]
cached releases are instantly available on your debrid service, uncached releases need to be downloaded by your debrid service first. I would recommend you keep the setting regarding cache status as the following:

    1) cache status  requirement :   cached

if you dont mind adding uncached releases to your debrid service, change this rule to:

    1) cache status  preference :   cached

This will prefer cached releases, but will also download uncached releases if no cached ones are available.

**Comment by itsToggle** [comment]
This still does not explain why you would get the error message in your original comment though. You dont have any other versions defined than this one? If I copy the settings that youve posted, I can scrape for releases without issue.

**Comment by dspdhckr** [comment]
I am still having an issue with the settings you mentioned. Let me try adding the code again to my file and run it.

Meanwhile,

Attaching the code of my settings.json here,

`{
    "Content Services": [
        "Plex",
        "Trakt",
        "Overseerr"
    ],
    "Plex users": [
        [
            "Plex.user",
            "Random String for privacy"
        ]
    ],
    "Plex auto remove": "movie",
    "Trakt users": [
        [
            "User 1",
            "Random String for privacy"
        ],
        [
            "User 2",
            "Random String for privacy"
        ],
        [
            "User 3",
            "Random String for privacy"
        ]
    ],
    "Trakt lists": [
        "User 1 watchlist",
        "User 2 watchlist",
        "User 3 watchlist"
    ],
    "Trakt auto remove": "movie",
    "Overseerr users": [
        "all"
    ],
    "Overseerr API Key": "",
    "Overseerr Base URL": "http://localhost:5055",
    "Library Service": [
        "Plex Library"
    ],
    "Trakt library user": [
        "Random User for privacy",
        "random string replacing original content for privacy"
    ],
    "Plex server address": "http://localhost:32400",
    "Plex \"movies\" library": "1",
    "Plex \"shows\" library": "2",
    "Plex library check": [],
    "Sources": [
        "rarbg",
        "1337x"
    ],
    "Versions": [
        [
            "1080P SDR",
            "both",
            "true",
            [
                [
                    "cache status",
                    "preference",
                    "cached",
                    ""
                ],
                [
                    "resolution",
                    "requirement",
                    "<=",
                    "1080"
                ],
                [
                    "resolution",
                    "preference",
                    "highest",
                    ""
                ],
                [
                    "title",
                    "requirement",
                    "exclude",
                    "(\\.DV\\.|3D|\\.H?D?.?CAM\\.)"
                ],
                [
                    "title",
                    "requirement",
                    "exclude",
                    "(\\.HDR.\\)"
                ],
                [
                    "title",
                    "preference",
                    "include",
                    "(EXTENDED|REMASTERED)"
                ],
                [
                    "size",
                    "preference",
                    "lowest",
                    ""
                ],
                [
                    "seeders",
                    "preference",
                    "highest",
                    ""
                ],
                [
                    "size",
                    "requirement",
                    ">=",
                    "0.5"
                ]
            ]
        ]
    ],
    "Special character renaming": [
        [
            "&",
            "and"
        ],
        [
            "\u00fc",
            "ue"
        ],
        [
            "\u00e4",
            "ae"
        ],
        [
            "\u00f6",
            "oe"
        ],
        [
            "\u00df",
            "ss"
        ],
        [
            "\u00e9",
            "e"
        ],
        [
            "\u00e8",
            "e"
        ],
        [
            "sh!t",
            "shit"
        ],
        [
            ".",
            ""
        ],
        [
            ":",
            ""
        ],
        [
            "(",
            ""
        ],
        [
            ")",
            ""
        ],
        [
            "`",
            ""
        ],
        [
            "\u00b4",
            ""
        ],
        [
            ",",
            ""
        ],
        [
            "!",
            ""
        ],
        [
            "?",
            ""
        ],
        [
            " - ",
            ""
        ],
        [
            "'",
            ""
        ],
        [
            "\u200b",
            ""
        ],
        [
            " ",
            "."
        ]
    ],
    "Rarbg API Key": "wgekqzidp4",
    "Jackett Base URL": "http://127.0.0.1:9117",
    "Jackett API Key": "",
    "Jackett Indexers": [],
    "Jackett Categories": [],
    "Jackett Filters": [],
    "Prowlarr Base URL": "http://127.0.0.1:9696",
    "Prowlarr API Key": "",
    "Debrid Services": [
        "Real Debrid"
    ],
    "Tracker specific Debrid Services": [],
    "Real Debrid API Key": "",
    "All Debrid API Key": "",
    "Premiumize API Key": "",
    "Debrid Link API Key": "",
    "Put.io API Key": "",
    "Show Menu on Startup": "false",
    "Debug printing": "false",
    "version": [
        "1.31",
        "Settings compatible update",
        []
    ]`

**Comment by itsToggle** [comment]
okay found the error. Youve defined your "HDR" exclusion rule to look like this `(\\.HDR.\\)`. A backslash is an "escaping" character, which means it will escape the following character. You accidentally escaped the ")" in this rule, which is why regex is complaining that a ")" is missing at the end of this definition. Change that rule to:

 `(\.HDR\.)`
 
 This should fix it. I will implement a check for correct formatting of these rules in the next commit.

**Comment by dspdhckr** [comment]
Hey thanks a lot, it is working now... But in the settings.json the rule is like this, (\\.HDR\\.) So I was bit confused during the change after your suggestion, but now it is working so thank you. By the way, must say, this rule section look way more convenient than the previous one.

**Comment by itsToggle** [comment]
Thats what I was hoping for! Thanks :)

Yeah the settings.json file escapes the backslash twice :)
