### ISSUE TITLE
Implement automatic removal of content from public trakt lists

### ISSUE THREAD

**Issue by dvdgorila** [itsToggle/plex_debrid#180]
Hi itsToggle, 

I've created a custom trakt list and it doesn't appear that the release is being removed once added to my library. I do see in the output that it states its being removed, but it's not. Anything I need to do on my end to get this working?

(dont want to use watchlist since I have other things that rely on it)

**Comment by itsToggle** [comment]
Hi, currently only stuff from your watchlist can be removed. When I implemented the "add a public list" option, I did not imagine that the user was the owner of that public list. This can definitely be implemented :)

**Comment by itsToggle** [comment]
implemented in v2.30
