### ISSUE TITLE
Add ARM 64 Docker Image

### ISSUE THREAD

**Issue by joshali1990** [itsToggle/plex_debrid#183]
Can you add ARM 64 support to the docker image? I believe you just have to add the following to your actions. 

        with:
          platforms: linux/amd64,linux/arm64

**Comment by itsToggle** [comment]
Looks like that failed.. Ive added that line to the last step "Build and Push"

![image](https://user-images.githubusercontent.com/71379623/195895725-9450493d-b14e-4249-bcaa-d099c724d3f8.png)
