### ISSUE TITLE
Autoscan Integration

### ISSUE THREAD

**Issue by godver3** [itsToggle/plex_debrid#185]
Have you considered integration with the manual trigger option of Autoscan?

https://github.com/Cloudbox/autoscan

This would remove the need for scanning a full Plex library section and instead can just scan the newly added folder. I believe passing the anticipated folder plus the Autoscan url is essentially all that’s needed.

**Comment by itsToggle** [comment]
If you take a look at #182 ive mentioned this exact tool :)

**Comment by godver3** [comment]
> If you take a look at #182 ive mentioned this exact tool :)

Whoops! Thanks.
