### ISSUE TITLE
Refresh / scan after download not working

### ISSUE THREAD

**Issue by codevski** [itsToggle/plex_debrid#189]
It seems like everything is working fine besides the refresh. It states It's refreshing the library category, but it might not be, I have to manually trigger a scan within plex web ui.

Happy to paste any logs that you need.

**Comment by itsToggle** [comment]
Alright, setting is implemented.

**Comment by codevski** [comment]
Hey thanks for the quick reply, I have pulled the latest image and now see that it displays the category name instead of the number which is nice to confirm that its looking at the right one but refreshing still seems to not be happening... I can see 

```[2022-10-19 00:29:28.411962] [plex] refreshing show library section/s: "RD Shows"```

But still not being processed on plex

**Comment by itsToggle** [comment]
I would still recommend using my rclone fork, the official WebDAV is still worse for various reasons detailed in the plex_debrid and rclone_rd readme.

what mount command are you using?

**Comment by codevski** [comment]
what OS are you running this on?
- So for plex running in docker( linuxserver image to be exact) (network set to host)


what content services are you using?
- Plex and Trakt

do you have more than one plex user added?
- At the moment just the single plex user

what rclone_rd version and mount command are you using?
- Version v1.58.1-rd.1.8
- `sudo ./rclone-linux mount realdebrid: /apps/rd --daemon --allow-other --uid 1024 --gid 100 --dir-cache-time 10s --vfs-cache-mode full`
- (using uid and gid that are set as other docker services)

And I'm assuming the shows do show up if you manually refresh?
- Yeah if I run the refresh manually it will find the files and download all the meta as well etc

**Comment by itsToggle** [comment]
Hm, that all sounds like it should work, I can't see anything wrong with your mount command and the rest of the setup.

Does the status wheel on the top right of the Plex webui start spinning when plex_debrid says "refreshing library section X"?
If not, what's the Plex server address you've entered into plex_debrid (if not sensitive) and does plex_debrid print any errors with the UI Setting "debug printing" enabled?

**Comment by codevski** [comment]
Sorry to get back late I did a complete reinstall of the home server just to make sure it isn't something on my end. 

One thing I have noticed after a download is complete doing a manual refresh doesnt detect the fil BUT if I cd into the mounted folder to make sure the file exists and then do a manual refresh it picks it up. This to me makes me think the refresh works but the file doesnt get detected / updated until I cd into the directory....

**Comment by itsToggle** [comment]
Definitely try out the official rclone, but I don't think thatll make much difference. You could decrease the "--dir-cache-time" even further to something like "--dir-cache-time 5s".

Other than that I'm afraid I don't know what could cause this - its working for me with the current settings you have :/

**Comment by codevski** [comment]
Yeah tried out the official rclone and it picks it up instantly so looks like something wtih this fork that it doesnt like :(

**Comment by itsToggle** [comment]
So does the plex_debrid refresh work? Or is the official rclone with realdebrid WebDAV just detecting changes immediately on a manual refresh?

**Comment by itsToggle** [comment]
In either case, a refresh does need to be called for the content to appear on your harddrive. Refreshing your library and cd-ing / ls-ing the directory is doing the same thing in the eyes of rclone.

**Comment by codevski** [comment]
Yeah so the plex_refresh was working fine all along, seems like the issue around the system not knowing when a new file was added to the mount.

What was happening plex does in fact refresh its library from plex_debrid but since it wasn't detecting any new files it instantly stoped.

Once I navigated to the mounted drive and do a `ls` while viewing the mount with -vv I can see it detects the changes then returning to plex and doing a manual refresh it picks up the files.

So with the official rclone version, it works fine with the same mount options, once plex_debrid pushes a refresh plex instantly picks up the file change and updates like normal.

If there are any logs you would like just let me know :)

**Comment by codevski** [comment]
Yeah with the fork manual refresh is required and with the official rclone the refresh happens automatically no manual refresh from me is required

**Comment by itsToggle** [comment]
Alright! Glad the plex_debrid part is working. I'll see what I can do regarding rclone_rd. This does not seem to be an issue for me / most other users of rclone_rd, but perhaps there is something I can tweak.

**Comment by piratsch** [comment]
I'm having the exact same problem.
I think it is because there are now two folders that are mounted, and rclone only refreshes when there is a change in the root directory of the mount.
I now have a script running in the background to just refresh the contents all the time :)

**Comment by itsToggle** [comment]
you got a source for that information? rclone_rd will refresh when any directory is accessed. These directories are accessed when a refresh call is made to your plex server, so rclone will refresh them.
