### ISSUE TITLE
Quality upgrades for downloaded content

### ISSUE THREAD

**Issue by itsToggle** [itsToggle/plex_debrid#192]
Someone mentioned on discord that it would be nice if plex_debrid could regularly check for available upgrades to your existing content.

**Comment by bbccdd** [comment]
Indeed, similar to the 'monitored' [for better versions] state in servarr starr apps like radarr.

**Comment by bbccdd** [comment]
How are different quality profiles and release groups handled in plex_debrid please? For inspiration: https://trash-guides.info/Sonarr/Sonarr-Release-Profile-RegEx/

**Comment by itsToggle** [comment]
check out the "Defining versions to download" section of the readme. You can define an unlimited amount of versions to look for, each with their own "triggers" and "rules".

**Comment by bbccdd** [comment]
That is sweet indeed! I should have unfolded the documentation sections :) And you're saying your not a professional programmer.. great thinking to make matters that simple!

**Comment by piratsch** [comment]
Is it already possible to "rerun" the scraping for previously added content?
I would really like to have x265 and x264 versions...

**Comment by itsToggle** [comment]
> Is it already possible to "rerun" the scraping for previously added content? I would really like to have x265 and x264 versions...

no, but this is a planned feature

**Comment by arjanterheegde** [comment]
Also waiting for this feature, would be a great update for the future version of plex debrid 👍.

**Comment by itsToggle** [comment]
Is / will be implemented in v2.73 👍
