### ISSUE TITLE
[Feature request] support for jellyseerr

### ISSUE THREAD

**Issue by krishne35** [itsToggle/plex_debrid#195]
It would be cool to have [jellyseerr](https://github.com/Fallenbagel/jellyseerr) support :)

**Comment by itsToggle** [comment]
implemented a way to match overseerr content to the trakt media type, which would allow jellyseer to be set up instead of overseerr (they use all the same api endpoints). This update is currently in testing, you could already check it out on the experimental branch. There will be bugs though.

**Comment by itsToggle** [comment]
implemented in v2.20
