### ISSUE TITLE
Overseerr Issue with Series

### ISSUE THREAD

**Issue by godver3** [itsToggle/plex_debrid#201]
I have noticed that Overseerr series seem to stop being checked through a script restart. I have a series that is showing as requested, and the newest episode is available, but the script doesn’t seem to recognize it. If I manually remove the request and re-add it in Overseerr the request is picked up.

**Comment by godver3** [comment]
Closing - I see this issue is known.

**Comment by itsToggle** [comment]
Yeah I want to make the Plex library monitorable to solve this :)
