### ISSUE TITLE
Request: Anime Library

### ISSUE THREAD

**Issue by jakeau** [itsToggle/plex_debrid#202]
G’day, 
Probably more of an issue with scrapers but for the life of me I haven’t been able to get any English dubbed Anime, when getting anime I will get maybe 1/10 I add to the wish list. 

My request is it possible to have movies, TVs, anime libraries within plex? 

Thanks for your time.

**Comment by itsToggle** [comment]
Sadly anime releases aren't following any naming scheme. Instead of typical releases titled "some.show.S01" you get something like "some.show.1-1000", which is impossible to scrape for automatically.

Just add these shows manually :)
