### ISSUE TITLE
[plex] error: couldnt refresh libraries

### ISSUE THREAD

**Issue by moneill29** [itsToggle/plex_debrid#206]
when I add something to my watchlist this  shows up. i'm not sure how to fix it
![Screenshot 2022-10-27 003055](https://user-images.githubusercontent.com/60466135/198158019-5ad3023b-dfa5-4f1e-9f87-933b2bf6b120.png)

**Comment by itsToggle** [comment]
Go to Settings/Library Services/Library update services/ and edit the plex libraries that are supposed to be refreshed after a successful download :)

**Comment by itsToggle** [comment]
btw, why did you choose trakt as your library collection service? The library collection service is used to determin your current media collection - If you are running a plex server, Id highly recommend you set your library collection service to plex.

**Comment by moneill29** [comment]
Hey I managed to get everything working for me perfectly! It's a really good service and I really appreciate you putting all this time into making something like this. The only thing I am having trouble with is allowing my friends to add things to the library. They can access my movies & shows but when they add something to the watchlist on their account it doesn't download on main.py. How can I fix this? Thank you again!

**Comment by itsToggle** [comment]
you need to add their Plex token to your plex_debrid Plex users. To do that, go to the Plex webUI and switch to their account. After that go to https://plex.tv/devices.xml and copy one of the tokens of this user. Now set up a new Plex user inside plex_debrid :)

**Comment by itsToggle** [comment]
ill mark this original issue as solved, feel free to ask about the plex user issue in this thread though.
