### ISSUE TITLE
Allow usage without Plex or Trakt

### ISSUE THREAD

**Issue by Pfuenzle** [itsToggle/plex_debrid#217]
Hi,
I just stumbled upon your program today and wanted to set it up.
But while trying, I saw that it is required to use either Plex or Trakt as a list for the existing library.
Is it possible to bypass this behavior?

I'm planning to use plex_debrid as a backup method for sonarr/radarr and if I instantly want to watch a move without waiting for a download, so I don't mind if a movie is duplicated in my library.
Because of this, the Plex/Trakt requirement is not needed for me and hinders me in actually using plex_debrid.

Is there a way to bypass the library check?

**Comment by itsToggle** [comment]
Hey, that's sadly not possible as of now. What content service are you planning on using, that a connection to Plex/Trakt to check the current media collection is hindering you?
I'll mark this as an enhancement, perhaps I'll find the time in the future.

**Comment by itsToggle** [comment]
Looked into this and this wont be possible. Using only over/jellyseerr to search for content would be limited by only being able to search by IMDB ID, which is not widely implemented. You wont get around connecting this to at least one service that can be used to get some info on the movie/show, and I dont see a problem with connecting the current media library of that service with plex_debrid if the service is already connected anyways. Ill shelve this for now.
