### ISSUE TITLE
Adding trakt account causes exception in newest version

### ISSUE THREAD

**Issue by mallah94** [itsToggle/plex_debrid#223]
![screenshot_Bug](https://user-images.githubusercontent.com/44344163/199575438-482741e9-8e2f-489e-b06a-8e396def868e.PNG)

during initial setup, choosing Trakt as content service i can not add user. adding any user causes the exception seen in the picture attached.

**Comment by itsToggle** [comment]
Thanks for reporting. Trakt seems to give a 429 response when requesting a token sometimes, which I did not account for. You should be able to get this running by simply trying again a few times. In the next version there will be an error message displayed regarding this issue :)

**Comment by mallah94** [comment]
Nice while we are at it, adding prowller (didn't test yet with other sources) causes a json encoder exception if the url has a "/" at the end of the url. Is this already known?

**Comment by itsToggle** [comment]
Yeah, sorry.. I haven't implemented any value checks at all for older settings. All new ones should check the user input, but the old ones rely on a little standardized system I wrote that didn't allow for individual value checks. I'm slowly upgrading them all to incorporate these checks but it takes a while. Thanks for reminding me though!

**Comment by mallah94** [comment]
Anytime mate 💪💪

**Comment by itsToggle** [comment]
ill close this initial issue for now :)
