### ISSUE TITLE
Is there a way to trigger a version by user ?

### ISSUE THREAD

**Issue by JULIENBZH** [itsToggle/plex_debrid#224]
Something like : User 1 looking for 1080p version and User 2 720p.
It would allow us to "choose"  to get a version by switching user.

**Comment by itsToggle** [comment]
Oh that's an interesting idea! Yeah that could be implemented. I'll notify you once I've added this.

**Comment by JULIENBZH** [comment]
Thank you very much ! You already did a really good job with the script !

**Comment by itsToggle** [comment]
implemented this in the latest version :)

**Comment by JULIENBZH** [comment]
Wow, your fast ! well done and thank you.
