### ISSUE TITLE
jackett and prowlerr issue

### ISSUE THREAD

**Issue by filippezer** [itsToggle/plex_debrid#234]
Script finds releases seems to not be able to detect cached torrents. I am using torrentleach for trackers

**Comment by itsToggle** [comment]
please give a little more information about your setup. What debrid service are you using, and why do you think it can't detect the cache status?

**Comment by filippezer** [comment]
real-debrid. When I use rarbg for example it will find the release cached just fine but if I do it through jackett it will have cached: empty and not find it for the same title

**Comment by itsToggle** [comment]
that might be because there simply is no cached release from your jackett indexers. torrentleach is a private indexer after all, and these usually don't allow the usage of realdebrid - so you most likely won't find any cached releases from torrentleach.

**Comment by itsToggle** [comment]
If the only reason you assume that the cache check is not working is because it's not finding cached releases from this indexer, I will close this issue.
