### ISSUE TITLE
Issue mounting drive

### ISSUE THREAD

**Issue by inputuserhere** [itsToggle/plex_debrid#261]
Whenever I'm running ./rclone-linux mount rb: /home/plex/storage: --dir-cache-time 10s

Error:
**2022/11/21 03:05:28 NOTICE: Config file "/home/plex/.config/rclone/rclone.conf" not found - using defaults
2022/11/21 03:05:28 Failed to create file system for "rb:": didn't find section in config file**

Also, how can I enable it as a background service? systemctl enable rclone-linux cannot locate a rclone-linux.service file.

When setting up folders, do I just make directories? 

**Create a plex 'movie' library of the mounted virtual drive or add the virtual drive to an existing 'movie' library.
Create a plex 'shows' library of the mounted virtual drive or add the virtual drive to an existing 'shows' library.**

Using Debian 11.

**Comment by itsToggle** [comment]
try running the command with sudo privilege? it sounds like you are trying to run rclone as a non root privilege user ("plex"), which is probably why rclone can't find the config file.

When mounting to a folder, remove the ":" at the end of your mount location: `./rclone-linux mount rb: /home/plex/storage --dir-cache-time 10s`

You can run it as a background service by adding "--daemon"

the Plex library creation steps are referencing Plex libraries, not folders. Create a new library, select the type "movies", point it to the mounted "movies" and "default" folder. Create a new library, select the type "shows", point it to the mounted "shows" and "default" folder.

**Comment by itsToggle** [comment]
Just run the config again with "sudo. /rclone config"
