### ISSUE TITLE
movies downloading to wrong folder?

### ISSUE THREAD

**Issue by pa-st** [itsToggle/plex_debrid#277]
So, for weeks i was puzzled why one single movie won't download. This movie being the 2009 Star Trek.
So, it turnes out, it's downloading to the "shows" folder in my realdebrid for some reason? Everything else works fine, but this one movie refuses to go to the movies folder, even if i manually move it there..

**Comment by itsToggle** [comment]
What's the exact torrent title?
rclone_rd uses regex definitions to sort movies and shows into their folders, so you can't directly move items from one folder to another. You can edit these regex definitions in the advanced settings of your rclone_rd realdebrid remote. Your movie most likely contains some number seperated by a "-", which is a common anime show title format - hence the wrong sorting. 
If you dont want to edit these Settings, you could also just add that single folder from the shows folder to your plex movie library, by editing the library folders.
