### ISSUE TITLE
use jacketts "test:passed" filter

### ISSUE THREAD

**Issue by joshali1990** [itsToggle/plex_debrid#278]
Hey not sure why, but I've been getting the following error lately when scraping results with Jackett:

``` 
[...] "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
Exception in thread Thread-847 (multi_init):
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self._target(*self._args, **self._kwargs)
  File "/Users/joshali/plex_debrid-main/scraper/services/jackett.py", line 148, in multi_init
IndexError: list assignment index out of range
[...]
```

**Comment by joshali1990** [comment]
Nevermind, Torrentz2eu was down and it was causing the error. Removed and it's working now. Is there any way to implement a check for broken indexers?

**Comment by itsToggle** [comment]
Alright I don't know why a jackett indexer that's down would cause the thread to crash, I'll check that out.
There is the option to only query jackett indexers that have passed a "test", but the documentation is unclear on it. It's unknown whether or not this test is actually performed whenever a scraping attempt is made, or this test needs to be performed seperately. I don't currently have the time to check it out so I will change this issue into a more clearly stated request to add this check to the plex_debrid Jackett implementation.

**Comment by itsToggle** [comment]
added in v2.50
