### ISSUE TITLE
require trakt user before allowing to add public list

### ISSUE THREAD

**Issue by itsToggle** [itsToggle/plex_debrid#279]
This leads to the script crashing otherwise

**Comment by itsToggle** [comment]
I don't think this is related - I'm unsure what happened there. The second EOF error suggests that you are running plex_debrid in a terminal that doesn't allow any input. 
The first error could be a byproduct of that.

**Comment by codevski** [comment]
Yeah, its running in a container without input, keeps restarting so Ill try run it manually to see if it requires input else I might create a ticket if I cant figure out the problem
