### ISSUE TITLE
RealDebrid issues

### ISSUE THREAD

**Issue by BluePotatoBP** [itsToggle/plex_debrid#29]
Hey, since the last time I got the script to work I've had quite a few issues;

1. Any time I would add something to the watchlist, it scrape, download, and I'd be able to watch it but it kept erroring out saying either the plex transcoder crashed or that I don't have good enough internet connection (100d/60u) and most of the time it did play, the video would just be a smeary mess. I tried different indexers, and I doubt that was it but it did improve the scraping time. I also tried both on my desktop and phone and it's about the same, smeary mess and dies after maybe 10 seconds.

2. Since then I left it for a few days as I didn't have time to mess around with it, but now that I've come back to it I got a real-debrid error 8, essentially saying I have a bad token. (removed id just to be safe idk)
![image](https://user-images.githubusercontent.com/52742857/174451989-de161796-8cb7-49d4-ab95-73ba78acdd6a.png)
![image](https://user-images.githubusercontent.com/52742857/174452029-25d51fe9-f9d4-4873-b28f-457e78861489.png)

Did the token expire or did I get banned? This genuinely makes no sense to me anymore.
Also just to mention, I got a refund and used your referral code, hope you got some free days :)

**Comment by BluePotatoBP** [comment]
Oh and it also skips around quite a bit, like I just pressed play for the first time on this movie and it did play ~3s and then skipped to 30 and turned to mash.
![image](https://user-images.githubusercontent.com/52742857/174452225-a48b324d-5fc1-4b0d-b38d-9d42291c1b5f.png)

**Comment by itsToggle** [comment]
Hey, thanks for using the code, makes me even more sorry you are experiencing these errors.

 1) The playback issues look like some kind of fault with rclone. Did you try restarting rclone? What command are you using to mount? There are quite a few settings that you could try, which might improve your playback. One I would suggest is expanding or lowering the chunk size in which rclone downloads your files. The default is 128M I believe, you could try lowering it to 64M for example. The mounting tag would be: --vfs-read-chunk-size 64. 
Have you checked whether or not plex is transcoding the movies you watch? Realdebrid will work best if you play in original quality.

2) Have you checked wether your api key has changed? Perhaps after the refund your token was renewed/ you have a different account now,

**Comment by BluePotatoBP** [comment]
_Ok to summarize what happened: slow ssd is a big no no, and still couldn't get much functionality._

1. Yeah, I restarted rclone multiple times since, even the whole computer.
I'm using `rclone cmount funny-remote: Y: --dir-cache-time=10s --vfs-cache-mode=full`.
I just copied the one from your readme, and tbh I haven't looked into the other settings as I didn't have time this past week.

I did check transcoding and even tried turning everything down to the minimum and upped the buffer size, to no avail.
![image](https://user-images.githubusercontent.com/52742857/174460850-628844e9-9c91-4765-8ffd-8246b148d412.png)
It gets to exactly 36 seconds each time and then stops with the error **h3 (Decode)**
![image](https://user-images.githubusercontent.com/52742857/174460897-1b29f2b7-bd93-4b84-8e4e-c260e8e1a2a7.png)
And if I completely disable video stream transcoding it says there isn't enough CPU for that. Alright...

Then I tried it with the tag you gave me, using 64M and 256M, changed the cache drive and it seemed to actually work for a solid 10 minutes.
(`rclone cmount funny-remote: Y: --dir-cache-time=10s --vfs-cache-mode=full --vfs-read-chunk-size 64M --cache-dir=D:\RCloneCache`)

And then out of the blue this happened:
![image](https://user-images.githubusercontent.com/52742857/174461752-273bdbd5-8ed8-4f91-bbf6-a18be766aaac.png)
This one I have no clue what it means. (also it's only happened once, haven't seen it since)

64M seems to have helped somewhat (as in, it decodes longer now). 


So I sat down to watch the movie but, again, after everything I tried it still just randomly shits the bed:
![image](https://user-images.githubusercontent.com/52742857/174461760-ce935029-81d2-4d38-8e66-965097c1c7a3.png)
^^^ There is clearly enough buffer for it to continue playing but it just refuses. I tried buffer sizes of 60, 120, 240, 300, 600. 
(Yes I tried combinations of buffer sizes and the two different size cache flags. just hoping something would work)

At this point I'm starting to believe the files are corrupted in some places or I'm getting those random cosmic bit flips that screw everything up 🤷

2. Yes that's the first thing I went to check and the key is exactly the same. Sorry I should have mentioned it, although, I don't seem to be getting that error anymore.

3. Kind of unrelated but GPU decode should definitely not be a plex pass feature, at that point I might as well buy subscriptions for all the streaming platforms that exist. Not your fault obviously, just blowing off some steam...

Also sorry for the essay :)

**Comment by itsToggle** [comment]
That rclone error indeed looks weird.. might have been one of those cosmic bitflips ;)
1) Alright, that already rules out a whole lot of possibilities! One way to check if the issue is only with plex would be to just open the movie with VLC or some other media player. 
If everything plays fine when directly opening the file, plex should be able to direct play it too. Its very weird that Plex tells you you dont have enough CPU performance for direkt play, since direct play wouldnt need transcoding at all! When watching through the browser, Plex is sometimes forced to transcode since browsers don't support all file formats. You could try to download the Plex HTPC (Home Theater PC) client, which should support more formats for direkt play. 
If the files seem to be broken when playing with VLC, the issue lies either with rclone or the file itself. To check if the file works properly, you could just download it from realdebrid to your local disk and try to play it with VLC. 
If everything works fine with the downloaded file, the issue lies with rclone. There are some more tags that we could try: `--vfs-cache-mode off` for example. If the issue really is with rclone we can definitly try some more things.
If the file really is broken (which is pretty unlikely i think) your only option would be to download a different release and try again :/

2) Does the script still work when downloading new content? From the first logs you showed it almost looks like it works fine despite the error.

3) Yeah. Plex really isnt great, but i still think its the best option out there.. If you are running this on windows, you wont be able to use your GPU for transcoding anyway. Plex for windows only supports CPU hardware en/decoding as far as i know.

**Comment by BluePotatoBP** [comment]
1. Ok it turns out chrome bugs something fierce and absolutely refuses to play the video at original quality without any transcoding. Plex HTPC definitely works and so does the mobile app (couldn't tell you why it didn't work before, makes no sense but ok). It's still having issues with randomly stopping or skipping small stretches of video. Opening the file with VLC works for a bit but has the same issue of corruption? Then downloading a file from real debrid works completely fine with no artifacts or skipping. The `--vfs-cache-mode off` flag didn't have any noticeable impact so I just reverted to 64M of cache. 

How would I download a different release? 
I removed some indexers that were slow but that didn't change anything. 

Also both movies I tried apparently are h.264/5
![image](https://user-images.githubusercontent.com/52742857/174496309-c570bf3a-65a9-4ec3-9295-cd41587aa4f7.png)


2. It appears to have been a one off thing, haven't gotten the error since. I really wouldn't know what to tell you :(
3. Oh, well idk I googled GPU decoding for plex when I got those "not enough CPU" errors. The one answer I found was them telling off someone because they didn't have plex pass.

**Comment by itsToggle** [comment]
Alright, then the problem lies with rclone :) rclone doesnt seem able to keep up with plex. I would recommend you read the rclone mount dochmenation, but here are a few things you can try:

- Add this flag in addition to the chunk size flag: `--vfs-read-chunk-size-limit 128M` (could be better if its even less)
- Change the mount type to a network drive If you are on windows

Here's the entire dochmenation: https://rclone.org/commands/rclone_mount/

**Comment by BluePotatoBP** [comment]
Hey, I tried that chunk size flag, even turned it down to 64M and changed the mounting drive to a network drive. 
And it was all going smoothly until about half an hour in, then the movie just restarted :c

Also sorry for the delayed response, it's taking even longer now that it sort of works to properly test it.

I genuinely don't know what flag I could use from the docs, I'm not very well versed in the science of virtual drives. Hope you understand. (Yes this is me asking to be spoon fed, please)

**Comment by BluePotatoBP** [comment]
See I put in my specs multiple times before but I just scrapped it when I found a solution to something, whoops :)

Windows 11
i9 9900k - 8 cores 16 threads up to 5.0ghz (only ever got to 100% when chrome was doing it's hardest not to play the video)
RTX 2070 (basically never touched)
16GB 3200mhz DDR4 (didn't see much over 500mb of usage from plex/the script/rclone/jackett combined)
2tb m.2 SSD with 3000 read 2000 write (5-15% usage when the movie is playing)

You could say it's a bit outdated hardware or not suited for a server but it's not some 2009 laptop for sure.

I'm assuming this doesn't help much but the movie "Hustle" gets to 24m14s and restarts with my old command and the command you gave me. Increasing read-chunk-size, size-limit and buffer-size still gives the same results
![image](https://user-images.githubusercontent.com/52742857/174778246-6758f430-a87f-4d37-8ab5-0d9615a72c80.png)
^ No difference from 32M - 64M - 128M
Scrubbing forward and backward works fine, it only restarts when it gets to certain points... 

And on mobile when it gets to 24m14s it actually just jumps to 25m52s

Yes, Direct Play is enabled (HTPC):
![image](https://user-images.githubusercontent.com/52742857/174775150-8a49948b-8fe2-46fe-9815-8702c3f45f90.png)
I didn't see an actual "Direct Play" button (Mobile):
![Screenshot_20220621-123608_Plex](https://user-images.githubusercontent.com/52742857/174780910-1e2cca97-a929-48cf-9239-b121d4355c50.jpg)
![Screenshot_20220621-123712_Plex](https://user-images.githubusercontent.com/52742857/174781707-e93cbdcf-ae5e-44c3-8f4f-56f5c8ca0e46.jpg)

**Comment by BluePotatoBP** [comment]
Oh I feel really bad, you shouldn't have to google for me... I'll give it a shot as well :)

**Comment by itsToggle** [comment]
Alright I did find another option, try adding `--vfs-read-ahead 200M` ?

**Comment by itsToggle** [comment]
Are you using any sort of proxy or VPN?

**Comment by BluePotatoBP** [comment]
Might be completely unrelated but it's worth a shot, found a thread on plex [forums](https://forums.plex.tv/t/plex-does-not-support-eac3-5-1-anymore/203189) and people think it's something to do with the AC3 audio format, which is what one of the movies has
![image](https://user-images.githubusercontent.com/52742857/174790295-b778b92a-6f35-4516-90ea-2d26c135a970.png)
And the other doesn't
![image](https://user-images.githubusercontent.com/52742857/174790485-27248f2c-e4bc-4fc8-af52-e13bfb4fe94a.png)

`--vfs-read-ahead 200M` didn't work, still skips at 24:14

Not using a VPN but I am using the cloudflare 1.1.1.1 DNS

**Comment by BluePotatoBP** [comment]
And that codec theory is a nope.

**Comment by itsToggle** [comment]
Damn.. dns shouldn't be a problem either. You could try to set the Plex cache directory to some specific folder on your ssd, but I doubt that will help either

**Comment by itsToggle** [comment]
It could very well be the audio issue you mentioned, but movies with other audio stop playing too, right?

**Comment by BluePotatoBP** [comment]
You wouldn't believe it but that's exactly where I went.
This is me starting playback, scrubbing to 24:05 letting it get to 24:14 and it restarting playback.
![image](https://user-images.githubusercontent.com/52742857/174795763-7ec902c4-26e9-4921-b110-b8650d6535d2.png)
Kind of worried about `Content-Length is -1 (of total: -1)` and `- got played 0ms by account 1!`

And also:
![image](https://user-images.githubusercontent.com/52742857/174796075-9730f557-2e03-44d7-b726-3ea77d97a662.png)
Not sure what to think about this ^

**Comment by itsToggle** [comment]
I get the query parser issues too, I don't think that's a problem. 
I honestly have no idea how to proceed :/ Have you tried restarting you PC? :D 
You could try to reinstall plex, aswell as WinFSP (the software needed for rclone)..
I don't know. This might be some windows 11 issue with rclone or plex, I don't think there is much else I can do to help you unfortunately :(

**Comment by BluePotatoBP** [comment]
I don't know how up to date [this](https://support.plex.tv/articles/200375666-plex-media-server-requirements/) article is but it doesn't mention Windows 11, and yeah I've just done a reinstall of plex server, rclone and winfsp. I guess I'll just leave it and check in after a few weeks. I hope something magically fixes itself or an update does it. Thank you so much for your help and sorry for wasting your time once again :)

**Comment by itsToggle** [comment]
Hey, just a quick update: RealDebrid now implemented a WebDav server. This might be a long shot, but you could try to mount their webdav server with the official rclone software, instead of my fork. You can find instructions on the plex_debrid readme page.

Their Webdav server is currently in beta, and at the moment its definitly a feature-downgrade from my fork, but perhaps using the official software will fix your issues? May be worth a try :)
