### ISSUE TITLE
Syntax for versions to download

### ISSUE THREAD

**Issue by carloss66** [itsToggle/plex_debrid#291]
Can you please document the syntax? How are we supposed to use the . | \ ? characters? Is * allowed? I am trying to stop CAM, HDCAM, HINDI, C1NEM4, etc. but they are still getting scrapped.

**Comment by itsToggle** [comment]
It's official regex syntax, you can easily look this up with a simple google search or test it out on regexr.com

**Comment by itsToggle** [comment]
added this info to the readme
