### ISSUE TITLE
Deleted shows / movies get ignored when trying to download again

### ISSUE THREAD

**Issue by codevski** [itsToggle/plex_debrid#297]
So during the traktv api outage I deleted a bunch of shows and tried to redownload them again. I've noticed only newly added shows were being downloaded for example Yellowstone, only Season 5 E 6 and 7 were being downloaded and all other seasons and episodes were being ignored.

Only thing in logs I see is
```
[29/12/22 10:02:10] matching item: 'tmdb://73586' of service 'content.services.overseerr' to service 'content.services.plex'
[29/12/22 10:02:12] [plex] getting entire plex library ... done
[29/12/22 10:02:16] checking new content ... done
```

I'm guessing during the `getting entire plex library`  it still thinks it has the older files? Tried emptying trash manually on Plex and also have checked the box for empty trash on every scan still not working.

**Comment by itsToggle** [comment]
Have you made sure that these seasons are not marked as "watched" in your chosen library ignore service?
If you chose Plex as your library ignore service, go to the Plex Discover section in any Plex client and make sure that the seasons that aren't being downloaded are not marked as "watched".

**Comment by codevski** [comment]
Hrmm original value is "Plex Discover Watch Status" some were watched but not all, I changed it to an invalid option like "Plex Library" and shows starting to download. Is it possible to have an option to grab shows that are not present instead of watched? Just wondering how does this work with multiple users?

**Comment by itsToggle** [comment]
Im unsure what you mean. plex_debrid is downloading content that you dont already have, and that is not "ignored". plex_debrid needs to have a way to "ignore" content that could repeatedly not be downloaded. I personally use the Plex Discover Watch Status, so I can mark seasons as "watched" inside my plex client - this way I can stop unwanted seasons from being downloaded. You can pick a different service, such as your trakt watch status or a local file.
