### ISSUE TITLE
Scraping services error: Orionoid key expired

### ISSUE THREAD

**Issue by dd1512** [itsToggle/plex_debrid#298]
Hi team, 

After having an error with jackett
> error 404: it seems jackett is reachable, but there was an internal error.

, I bought 3 months of orionoid premium. 

I then removed all other scraping services in the settings.json file and put only Orion in there as below:
>"Sources": [
> "orionoid"
> ],

It gave me this error when running the automation: 
> [30/12/22 02:27:32] [orionoid] error: The API token has expired. Please renew the token.

I have created a new API key and inserted it in the settings.json file but it's still giving me the same expiry error above. 

Any help would be appreciated.

**Comment by itsToggle** [comment]
Please use the plex_debrid settings menu for that API key. Plex_debrid is getting it via oauth, you can't get this API key any other way than through the plex_debrid UI.
Start plex_debrid and go to /Settings/Scraper Settings/Sources/Edit/Orionid/API Key
