### ISSUE TITLE
[Overseerr] Partial series request - couldnt match content to plex media type

### ISSUE THREAD

**Issue by piratsch** [itsToggle/plex_debrid#307]
When I request parts of a series on overseerr, `plex_debrid` returns the following error
```[plex error]: couldnt match content to plex media type, no media of the same type found!```

Any ideas on what could be going on here?

**Comment by itsToggle** [comment]
That would suggest that you don't have any shows/seasons/episodes in your Plex library (at least as far as plex_debrid can tell).
You need at least one movie and one episode of a show, which are correctly matched by the default Plex metadata agent, in order for plex_debrid to match overseerr content to the Plex media type.
