### ISSUE TITLE
Issues with Prowlarr trying to resolve magnet/torrent links.

### ISSUE THREAD

**Issue by dreulavelle** [itsToggle/plex_debrid#322]
Keep seeing the `[prowlarr] error: resolver couldnt get magnet/torrent for release:` error everytime it tries to use Prowlarr. Wondering if maybe it's not connecting to the API or something? I can access prowlarr just fine and so can all of my *Arr apps too.

![image](https://user-images.githubusercontent.com/5782630/212550541-d8031df7-b9fb-41f4-a310-d98c9ca3f42c.png)
![image](https://user-images.githubusercontent.com/5782630/212550555-b5c1c039-b389-4750-8954-1b0871fdb09a.png)

**Comment by itsToggle** [comment]
first screenshot is definitly a bug, Ill look into this. second screenshot ive answered on discord (search "resolver timout" in the chat)
