### ISSUE TITLE
Unable to avoid camcorder releases

### ISSUE THREAD

**Issue by carloss66** [itsToggle/plex_debrid#335]
I am trying to fine tune the rules for movies so no camcorder releases are scrapped. This is what I have defined:
Rules:
1)  cache status  requirement :   cached
2)  resolution    requirement :       >=  1080
3)  resolution    preference  :  highest
4)  title         requirement :  exclude  (.DV.|.3D.|.H?D?.?CAM.|.HDTS.)
5)  title         requirement :  exclude  (.HDR.|.?C1NEM4.|.CAM.|.HDCAM.)
6)  title         requirement :  exclude  (.TeleSync.|.TeleCine.)
7)  title         requirement :  exclude  (.?Hindi.|.CAMRip.)
8)  title         preference  :  include  (EXTENDED|REMASTERED)
9)  size          preference  :   lowest
10) seeders       preference  :  highest
11) size          requirement :       >=  0.9

I don't understand why HDCAM and C1NEM4 crap is still getting scraped. With the above rules things like Black.Panther.Wakanda.Forever.2022.V2.1080p.HDCAM-C1NEM4.mkv gets scrapped.

**Comment by carloss66** [comment]
I also tried just (.DV.|.3D.|.H?D?.?CAM.|.HDTS.|C[iI1]NEM[aA4]) and the movie still gets scrapped.

**Comment by itsToggle** [comment]
as discussed on discord, I think you should be fine if you remove the dots before and after the H?D?CAM rule:
```
title requirement : exclude (\.DV\.|\.3D\.|H?D?.?CAM|HDTS)
```
