### ISSUE TITLE
Issue on Scraping?

### ISSUE THREAD

**Issue by dreulavelle** [itsToggle/plex_debrid#338]
![image](https://user-images.githubusercontent.com/5782630/213360851-a9a71d76-67a6-4ce7-8e47-4335611f2bbe.png)

It was just scraping sources based off an IMDB ID and came back with this exception. Don't really have any more info about it really unfortunately.

**Comment by itsToggle** [comment]
Thanks for the report!

**Comment by itsToggle** [comment]
did you manually edit the tracker specific debrid service setting?

**Comment by dreulavelle** [comment]
I did try and manually edit some stuff, and later I found that changes weren't persistent in the script UI. However Its possible I didn't restart the script so it could reload the config file. Not sure how often it reads the config for new changes.

![image](https://user-images.githubusercontent.com/5782630/213415872-5763590b-d31c-42c4-a517-cb4431564b05.png)

Come to think of it, I think there was 3 lines I removed that went to this?

**Comment by dreulavelle** [comment]
![image](https://user-images.githubusercontent.com/5782630/213416224-f1164fae-f8ee-4a88-97c9-b01113318299.png)

Yep.. I can't even remember what was there,  What's it supposed to be, or how can I regenerate it?

**Comment by itsToggle** [comment]
This setting is empty by default I believe. Are you still running into this issue now?
I had suspected that youve entered something into that setting through the settings.json file and that didnt match the correct format that the script expects.
