### ISSUE TITLE
Improve title queries

### ISSUE THREAD

**Issue by mash2k3** [itsToggle/plex_debrid#349]
Improve queries by checking probable title first then IMDB ID then possibilities.
This applies only if rarbg is the primary scraper

examples of issues below
![image](https://user-images.githubusercontent.com/1356023/213803003-222c0a51-ef4b-4f7a-9dac-030e43cf36dc.png)

![image](https://user-images.githubusercontent.com/1356023/213803184-fa8667f8-420f-46b6-854b-22b5d73ef6bb.png)

**Comment by itsToggle** [comment]
to combat the issue from the first picture (wrong match), im limiting the number of title aliases to 3. This will hopefully limit the allowed title deviation to more reasonable matches.
There is not much that I can do though. If trakt says that this is an alternative title for the same exact show, I dont know how I could tell that it isnt.

IMDB ID scraping is implemented in the way we discussed on discord.
