### ISSUE TITLE
Not Adding Media to Plex Library - Using QNAP NAS qpkg

### ISSUE THREAD

**Issue by Jezza96** [itsToggle/plex_debrid#352]
Hi there,

I recently installed the Plex Debrid qpkg (version 1.221126). https://www.myqnap.org/product/plex-debrid/
I followed all the instructions to set it up through SSH and set up a RealDebrid account.
When I add a movie/show to my watchlist, Plex Debrid correctly realizes I have added something to my watchlist, scrapes sources, find the best version and adds it to my RealDebrid downloads. It then correctly removes the movie/show from my watchlist.
Plex Debrid says it is refreshing the Movie/TV Show library, but it does not seem like any refresh occurs and the movie/tv show is not added to my 'Recently Added' media.

NAS is a QNAP TS-451+ running QTS 5.0.1.2248. Plex Media Server is running on the NAS and is version 1.30.1.6562.

I have asked for help on the QNAP discord but thought I would put the issue up here as well in case the issue is not just to do with the qpkg but is a broader issue.

Thanks in advance.

**Comment by itsToggle** [comment]
Hi, I have no idea what version they are using. This post also seems like auto-generated content with a donate link that isn't mine. I sadly won't be able to give support for this, nor would I even recommend using it. I'm not associated with this version of my script.
