### ISSUE TITLE
Scraper locks up

### ISSUE THREAD

**Issue by BIVEM** [itsToggle/plex_debrid#353]
After the latest update the scraper seems to lock up for awhile before it finds the releases (using Orion)

EDIT:It seems to actually be causes by Orion. I have it setup to scan for Orion first and if it can't find anything to fallback on raring, but simply having rarbg enabled seems to lock it up even if it never scrapes it.

EDIT2: Yeah after more testing it's definitely something with those 2 being pared together. Scraping with just Orion takes 5-10 seconds. Scraping with just rarbg takes 10-40 seconds, but scraping with them paired using the trigger to sort Orion before rarbg; it can take all the way up to 5 mins.

**Comment by itsToggle** [comment]
what do you mean by "paired"? Could you share the triggers you are using?

**Comment by itsToggle** [comment]
going through the code I dont see how there can be a causal connection. The plex_debrid scrapers sources are run in parrallel, they dont depend on each other. The rarbg api is very unreliable, it will return "too many requests" error codes 90% of the time. I currently think that you just had a little bad luck with the rarbg api.

**Comment by BIVEM** [comment]
> going through the code I dont see how there can be a causal connection. The plex_debrid scrapers sources are run in parrallel, they dont depend on each other. The rarbg api is very unreliable, it will return "too many requests" error codes 90% of the time. I currently think that you just had a little bad luck with the rarbg api.

I think them running in parallel might be the issue. Is there anyway I can make it always use orionoid and only rarbg if orionoid fails to find anything.

**Comment by BIVEM** [comment]
> what do you mean by "paired"? Could you share the triggers you are using?

Triggers:
A) retries          requirement :       <=  28
B) media type       requirement :    shows  
C) scraper sources  requirement :  include  orionoid
D) scraper sources  requirement :  include  rarbg

**Comment by maxexcloo** [comment]
I'm having issues like this too - if I enabled just the orion API it goes fast but if I enable 1337x + rarbg as well it slows to a crawl. Should I just disable 1337x/rarbg?

**Comment by itsToggle** [comment]
There is no way in which the version trigger or the combination of the scrapers could impact the scraping times, so the initial issue will be closed.

rarbg is unreliable. You might get responses instantly, or you might get "too many requests" errors for 60+ seconds before getting results.

orionid is unreliable. You might get releases instantly, or depending on their server load, you might get a response after 60+ seconds.

Be sure to update plex_debrid to the latest version. Try out jackett. try disabling rarbg and 1337x. That's all you can do.
