### ISSUE TITLE
Fatal error: failed to mount FUSE fs: fusermount: exit status 1

### ISSUE THREAD

**Issue by PsycheSoma** [itsToggle/plex_debrid#362]
Hello, I'm getting a few errors when I go through the process of mounting realdebrid.

Specifically running this command `./rclone-linux mount realdebrid: torrents --dir-cache-time 10s --allow-other`

I'm fed these errors
```
/rclone-linux mount realdebrid: torrents --dir-cache-time 10s --allow-other

<5>NOTICE: realdebrid root: --vfs-cache-mode writes or full is recommended for this remote as it can't stream Fatal error: failed to mount FUSE fs: fusermount: exit status 1
```

**Comment by itsToggle** [comment]
The first message you can ignore, Its a notice and not an error:

```
NOTICE: realdebrid root: --vfs-cache-mode writes or full is recommended for this remote as it can't stream
```

The second message is an actual, unrelated error:

```
Fatal error: failed to mount FUSE fs: fusermount: exit status 1
```

Do you have fuse installed on your system?

**Comment by PsycheSoma** [comment]
> The first message you can ignore, Its a notice and not an error:
> 
> ```
> NOTICE: realdebrid root: --vfs-cache-mode writes or full is recommended for this remote as it can't stream
> ```
> 
> The second message is an actual, unrelated error:
> 
> ```
> Fatal error: failed to mount FUSE fs: fusermount: exit status 1
> ```
> 
> Do you have fuse installed on your system?

Yes, looks like fusermount version 2.9.9 I'm very new to ubuntu (doing this on ubuntu server 22.04.1)

**Comment by PsycheSoma** [comment]
OMG, I just needed to run it as root. `sudo ./rclone-linux mount realdebrid: torrents --dir-cache-time 10s --allow-other`

Thank you for your attention, I can't wait to get this up and running!
