### ISSUE TITLE
add cache module to save ignore queue, downloading torrents, ... between restarts

### ISSUE THREAD

**Issue by itsToggle** [itsToggle/plex_debrid#374]

**Comment by I-am-PUID-0** [comment]
@itsToggle ideally cached to a folder similar to /config to support volume mapping in docker. :)

**Comment by itsToggle** [comment]
the first implementation for this only caches plex metadata, which seems to be the most pressing at the moment. This can be expanded to other data aswell, for which we will use new issues.
