### ISSUE TITLE
Stop logs clearing the screen

### ISSUE THREAD

**Issue by luisfavila** [itsToggle/plex_debrid#376]
Hi,

Great project, many thanks! 
I'm running this in a container along with plex, rclone_rd and a VPN using S6, the default service manager in `linuxserver` docker images.
It all works great except for the fact that plex_debrid clears the whole screen when logging. Is there a way to stop it doing so, and just write new messages normally? It ends up preventing me from reading logs from any other service, including plex.

Cheers

**Comment by itsToggle** [comment]
hey, plex_debrid is only clearing the screen when navigating the menus. The actual log from a run should not clear the screen, as its just printing new lines.

**Comment by piratsch** [comment]
Is there a reason why you run all in one container?
Having a separate container for each service makes it much easier to update the individual components.

**Comment by itsToggle** [comment]
good point, just run them in seperate containers.

**Comment by luisfavila** [comment]
@itsToggle I don't have any menus (it's set to run on start) and it's still clearing
@piratsch Because of VPN. I don't want to run a VPN on the whole server, just for rclone and plex_debrid

**Comment by itsToggle** [comment]
hm, you mean it clears after every new line that's printed?
Or just at the beginning? There is one clear command at the very start of the run, other than that I'm printing new lines and flushing the stdout, as is recommended when using threads.

**Comment by luisfavila** [comment]
Yap, I think it's right at the start. Surely not on every line.

**Comment by piratsch** [comment]
> @piratsch Because of VPN. I don't want to run a VPN on the whole server, just for rclone and plex_debrid
That shouldn't be a problem. You can have a VPN container and then route the individual containers that need to use the VPN through that container. 

Maybe [this](https://github.com/qdm12/gluetun), and [this](https://github.com/qdm12/gluetun/wiki/Connect-a-container-to-gluetun) in particular can help you.

**Comment by itsToggle** [comment]
alright I think I'll just remove the clear command when the script is run with "show menu on startup" = false. It's not needed anyways.
