### ISSUE TITLE
union rclone issue

### ISSUE THREAD

**Issue by roisec** [itsToggle/plex_debrid#397]
Hi @itsToggle 
The goal is to connect to my subtitles folder to the and join them to the movies folder
I am trying to union several sources with realdebrid remote mount..
I created union type storage and added the realdebrid: and local folder...
when I run cmount the union storage I got:
![image](https://user-images.githubusercontent.com/68992144/218107795-a1dfae43-7cbf-45e2-9bd8-f69762160ac8.png)

Can you help with this?

**Comment by itsToggle** [comment]
are you able to mount without the union?

**Comment by roisec** [comment]
Yes.
Everything is workings well! 
BTW, The union volume work with 2 local location, but with realdebrid volume it's not working.

**Comment by roisec** [comment]
https://github.com/rclone/rclone/issues/6650
I think there is bug on rclone..
Can you update your rclone version?

**Comment by itsToggle** [comment]
There is a new version of rclone_rd in the works that is based on the latest rclone version. It will be a little while before that's released though.

**Comment by itsToggle** [comment]
I will close this issue for now, since it can't be fixed directly. Will be revisited once the new version drops.
