### ISSUE TITLE
Feature request - Support add custom python filter version

### ISSUE THREAD

**Issue by roisec** [itsToggle/plex_debrid#398]
Hi @itsToggle , (BTW awesome project thanks)

I am planning to add your Plex debrid service scraping rule that will searching version with subtitles,if it there is no subtitles in my language then skip  torrent to the next torrent.
I would like to suggest the ability to everyone add custom filter version, easily add python code that did the checks and return True or false. 
I think it's may good feature, because everyone can write custom version or do whatever they want, it makes Plex debrid very flexible..
What do you think? Can you adding a guidelines for adding custom thing like this?

**Comment by itsToggle** [comment]
Plex_debrid already has completely customizable filters. They are called "version rules".

A subtitle rule like that has been suggested before, but it's almost impossible to implement.
What you can currently do is use the "file names" rule to only accept releases that have their subtitles in seperated ".srt" (or other format) files:
```
4) file names  preference  include  (srt)
```
Here's an example to prefer releases that have files with names that include "FRENCH" or "FR" and end have the format "srt".
```
4) file names  preference  include  (FR|FRENCH)(?=.*srt)
```
Most high quality releases don't have the subtitles as seperated titles though. They imbed the subtitles into the video container. It's not possible to prefer these releases, as that information is not accessable.

**Comment by roisec** [comment]
99% of the torrents are not contain SRT file with my language.. 
If you would say to check open subtitles site with the relevant language and version it will be good.

**Comment by itsToggle** [comment]
Yeah, searching open subtitles with the release name could work.
That would require authentication with the opensubtitles API though. Why not use something like the opensource project "Plex subtitle downloader" or the built-in Plex subtitle search? Both of these work great.

I can create a rule and trigger that lets you run your own python code though, that's a good idea for edge cases like this one.

**Comment by roisec** [comment]
Yes it is awesome,
Can we able add also the subtitles to the Plex metadata automatically? 
"Plex sub downloader" require Plex pass.

**Comment by roisec** [comment]
@itsToggle 
When do you think to finish for supporting the rule and trigger with custom python code?

**Comment by itsToggle** [comment]
I think I originally missunderstood your question here. You can already write your own python code and make a pull request to PD. check out the rules and triggers here: https://github.com/itsToggle/plex_debrid/blob/c1d221796e93670eee889c44a6f86b2ae93ce636/releases/__init__.py#L609
make a pull request with your own rules/triggers.
