### ISSUE TITLE
Allow multiple libraries, feed certain versions into each

### ISSUE THREAD

**Issue by markangeltrueman** [itsToggle/plex_debrid#403]
Feature request:

I have cases where i want a 2D version of a film to watch on standard screens, and a 3D version of a film to watch on my Oculus Quest 2 (over DNLA). Unlike in plex itself, there is no way to select which version of a film to watch on the quest apps such as Skybox and Bigscreen, so it would be really useful to be able to have a 2nd Movie library called "3D Movies" which uses the version download regex to only take 3D movies. (\.3D\.)

**Comment by itsToggle** [comment]
You can already do this, though this will be improved with the next rclone update.
You can use rclone filtering to filter your libraries. Just mount the same remote several times, adding different rclone filters to it. You can read about this in the official rclone documentation or here: https://github.com/itsToggle/plex_debrid#cloud-rclone-usage

But basically you can create a 3D library by mounting with:
```
instance 1) rclone mount realdebrid: X:3D --dir-cache-time 10s --include **3D**
instance 2) rclone mount realdebrid: X:2D --dir-cache-time 10s --exclude **3D**
```

**Comment by markangeltrueman** [comment]
Ahh, perfect. It works really well. I was not looking in the right place for a way to fix this. Thanks
