### ISSUE TITLE
plex_debrid Won't scrape movies that exist in other libraries

### ISSUE THREAD

**Issue by jamauai** [itsToggle/plex_debrid#418]
I have two movie libraries: one with locally stored content, and another I created to test plex_debrid. I noticed that when adding movies to Watchlist from the Plex Discovery area, even when the movie is not marked as played, if it already exists in the other movie library, it won't scrape.

**Comment by itsToggle** [comment]
This is intended behavior. You change this by limiting plex_debrids plex library scan to specific library sections, as described in the readme.

**Comment by jamauai** [comment]
I only specified the two test library sections during setup. I was wondering why during its scans it would still show as if it's touching all library sections. Will reconfigure and try again.

**Comment by itsToggle** [comment]
The setting you are probably referring to is the "library update service", not the "Plex library scan" setting that I was referring to.

Go to /Settings/library services/library collection service/edit/Plex library scan/

This is all explained in the readme though, under library collection services.

**Comment by jamauai** [comment]
Thank you, that was it. Appreciate the help.
