### ISSUE TITLE
Feature Request: Add Easynews support to plex debrid because Easynews is full of internal encodes from various familiar private trackers, while Real Debrid have way more scene encodes which means easynews has better quality videos that get downloaded and easynews has private trackers support built in compared to real debrid only having public trackers support that's not built in 

### ISSUE THREAD

**Issue by Pickymarker** [itsToggle/plex_debrid#426]
Feature Request: Add Easynews support to plex debrid because Easynews is full of internal encodes from various familiar private trackers, while Real Debrid have way more scene encodes which means easynews has better quality videos that get downloaded and easynews has private trackers support built in compared to real debrid only having public trackers support that's not built in

**Comment by itsToggle** [comment]
Their biggest plan has 150GB a month. If you were to mount this as remote storage, you would loose about half of that to idle rclone/Plex traffic. Leaving you with about 2 or 3 movies to watch.
This is not an addition that's worth the time investment.

Downloading Usenet stuff locally to watch it would be an option, but there are existing solutions for this out there and 150GB is still way too little.

**Comment by itsToggle** [comment]
also, keep the issue titles short and to the point

**Comment by ablakers** [comment]
FWIW Easynews does have deals they don't put on the main plans page (you can find the sign-up links on Reddit) which do have unlimited "web" download (not just NNTP)
