### ISSUE TITLE
Jackett timeout seems to not do anything

### ISSUE THREAD

**Issue by jakeau** [itsToggle/plex_debrid#428]
G'day, 

I kept being thrown the 'error: jackett request timed out' 

So changed   
 "Jackett resolver timeout": "1", to  "Jackett resolver timeout": "20",

It usually takes about 15 seconds when I manually search. 

However, I am still being hit with the same error message, it also seems that this error message is coming after much less than 20 seconds of the request... Seems as if this variable might not be doing anything.

**Comment by itsToggle** [comment]
That's because the resolver timeout is something different. If the "resolver" would time out, you would see an appropriate error message.

The error you are seeing is the regular timeout, which is set to 60 seconds.

**Comment by itsToggle** [comment]
If that's the entire error message, it seems that you are using a very old version of plex_debrid.

**Comment by jakeau** [comment]
I believe I was using a very old version, . 

Also thanks for this here are a few things that I use which I find useful. 

Docker compose script:

`version: '3.3'

services:
  plex_debrid:
    image: itstoggle/plex_debrid
    container_name: plex_debrid
    restart: always
    network_mode: host
    volumes:
      - /path/to/config:/config
`

Also, I have found that this for anime is very nice at finding anime dubbed titles and also good for splitting them out using using --include in rclone.

`                [
                    "title",
                    "requirement",
                    "include",
                    "((multi[ ._-]?audio)|(dual[ ._-]?audio)|(dub))"
                ],
`

**Comment by itsToggle** [comment]
nice!
