### ISSUE TITLE
Feature Request:  strengthen chache state importance for shows ( cache –preferred )

### ISSUE THREAD

**Issue by Helssiv** [itsToggle/plex_debrid#448]
> I recognized some behavior of plex_debrid which might not be the fastest:
> My setting is cache –preferred
> Following happened when looking for a show with a completed season:
> 
> Plex_debrid was first looking for a season pack – it found one season pack which was not cached and added this.
> When manually looking for the episodes one by one there are for each episode several cached links.
> 
> @itstoggle 
> So, I was wondering if it would make sense - for the case of no cached season pack found, with setting cached-preferred – to be first looking for the episodes one by one before adding an uncached pack.
> 
> E.g. :
> 1: scraping links 
> 2: scanning for season packs which are cached  |when failed ->
> 3: scanning for episodes which are cached |when failed ->
> 4: scanning for season packs which are uncached |when failed ->
> 5: scanning for episodes which are uncached |when failed ->

**Comment by itsToggle** [comment]
This is a great idea and can be implemented in much the same way as multi season packs are currently implemented;

- PD scrapes for the entire show (if more than 2 seasons are to be downloaded)
- PD checks if all seasons could be downloaded using cached multi season packs
- PD checks if all seasons could be downloaded using cached season packs
- PD compares the resolution this would result in and chooses the option that leads to the best quality

These steps could be performed for season scraping aswell.
