### ISSUE TITLE
[Suggestion] Scraper's default settings tweaks for versions

### ISSUE THREAD

**Issue by twitterblue** [itsToggle/plex_debrid#452]
Hi there,

I recently upgraded my script and would love to thank how better it has become over the time. There are less bugs and script runs very well now. Kudos to you. I just wanted to suggest one default version setting if we could change for some reason would be greatly appreciated. This setting I am using by manually tweaking but if you keep it by default then it would be great.

Nowadays, everyone using high tech screens which supports 4K resolutions natively. Hence, if you can tweak the settings to look for torrents <= 2160 rather than <=1080 version and complementing this if you could give preference to lower sized file for the same resolution would ultimately enhance the viewing experience. I mean I can stream 4K movie with 8 Mbps rather than watchin 1080P movie with 16 Mbps. I am not sure where I am correct with this regard because obviously higher bitrate means higher quality but 4K looks better than 1080P when I started scraping content likewise.

**Comment by itsToggle** [comment]
thanks! Ill leave the default version at 1080p, but I will write some more default versions which people can then activate and tweak.
