### ISSUE TITLE
Feature Request: Overseerr add newly released episodes

### ISSUE THREAD

**Issue by piratsch** [itsToggle/plex_debrid#458]
Hi!

Not sure if this is the intended behavior or not, but when I request a season in Overseerr it only adds the currently released episodes, without later checking again if new episodes are available.

Is there a setting that I need to change for this or is this a feature that has not yet been implemented yet?

Thanks a lot for your work! :)

**Comment by itsToggle** [comment]
Hey, new episodes should already be downloaded automatically for overserr requests.
Which season/s did you request? Which season are the newly released episodes from?

**Comment by piratsch** [comment]
So the most recent examples were family guy and the mandalorian.
I requested Season 3 of the mandalorian when not all episodes had been released yet.

**Comment by piratsch** [comment]
Now for example, Family Guy S21E18 has been out for a few days, and the season is requested in overseer:
![Fguy](https://user-images.githubusercontent.com/106690882/234647725-58dd9689-41b6-4bb4-8024-1d6fd3c2d986.png)
Not requested seasons look like this:
![Fguy2](https://user-images.githubusercontent.com/106690882/234647946-291af9d7-7218-4107-af27-2ab68424bb95.png)

**Comment by itsToggle** [comment]
That's very odd - as I said, this should already work. I'll try to find some time for the overseerr bugs in the coming days. In the meantime, have you asked the discord server if they run into similar issues? I have not had anyone else report this, and a bunch of people are using overseerr.

**Comment by itsToggle** [comment]
I assume this has been fixed, as no one else has been reporting this.
