### ISSUE TITLE
Can't stop scraping for files

### ISSUE THREAD

**Issue by amcgready** [itsToggle/plex_debrid#468]
I'll start off by saying I have a big library (according to plex debrid 9161). I initially ran plex debrid and everything was running great...until I realized my watchlist was fuller than I thought. The watchlist had over 1000 items in it. I have since cleared that watchlist entirely, but now whenever I close out of plex debrid and start the script again after getting metadata, it begins to search for items that were previously in the watchlist. Is there a way to fix this or restart plex debrid's setup entirely now that I have cleared out the watchlist?

**Comment by itsToggle** [comment]
did this resolve itself or is this still an issue? perhaps plex took some time to update the watchlist?

**Comment by itsToggle** [comment]
ill assume its fixed for the sake of cleaning up, but do comment if its still an issue.
