### ISSUE TITLE
Library empty, can't download

### ISSUE THREAD

**Issue by Siedjeey** [itsToggle/plex_debrid#472]
Hi, got everything working so far except for the fact that nothing is downloading because it keeps saying my library is empty?

[plex error]: Your library seems empty. To prevent unwanted behaviour, no further downloads will be started. If your library really is empty, please add at least one media item manually.

How can i fix this?

**Comment by piratsch** [comment]
You can manually add a torrent to the debrid service you use, which will then end up in the library. Then plex_debrid will start "downloading" (= adding content to your debrid service).
