### ISSUE TITLE
issue with mounting virtual drive 

### ISSUE THREAD

**Issue by ExtraTorrential** [itsToggle/plex_debrid#473]
When I try to mount the virtual drive a get a prompt from the terminal that the --vfs-cache-mode should be set to writes or full. When I set it to writes the drive shows up but it freezes my folder. Should I set it to full or is there something I'm doing wrong?

**Comment by piratsch** [comment]
I use `--dir-cache-time=10s --vfs-cache-mode=full` options.
This issue is a question about [rclone_RD](https://github.com/itsToggle/rclone_RD), not plex_debrid though
