### ISSUE TITLE
Only download single episode instead of multi or single season packs

### ISSUE THREAD

**Issue by rmkjr** [itsToggle/plex_debrid#478]
### Discussed in https://github.com/itsToggle/plex_debrid/discussions/477

<div type='discussions-op-text'>

<sup>Originally posted by **rmkjr** May 14, 2023</sup>
I would like to only allow downloads of single episode releases rather than multi or single season packs.  I find them easier to organize and mange, and plex often handles them better as their file names are more specific.

Looking here: https://github.com/itsToggle/plex_debrid/discussions/118#discussioncomment-3651170
You note the script will look for multi-season packs, followed by single-season packs, then single episodes.

I built the following version to use to only let through single episodes:
![image](https://github.com/itsToggle/plex_debrid/assets/8784055/cb7619f6-aa13-4db5-b7cf-ad23a85ef326)

In manually searching the scraper this works (including using "auto" to select the download:
![image](https://github.com/itsToggle/plex_debrid/assets/8784055/e4b07a0d-ec4b-41f7-981c-9faaa4f39434)

When running the script will download the first single episode of a season (SXXE01), but then for the remaining episodes it goes into and endless retrying state.  Even though they are available, sorted, and added in the manual scraper, the running script will never download them.
![image](https://github.com/itsToggle/plex_debrid/assets/8784055/495ce3f7-fda0-4091-8219-c7dfa6dba46d)

Is there something I can change to make it work this way, or is there a code change required?

Thank you!
</div>

**Comment by rmkjr** [comment]
This seems to be effecting normal fetching as well.  I removed the version preference to return it back to the more normal fetching settings.  I added the new Apple "Silo" show.  Season 1 of the show is still in progress of airing.  There is a release that contained episode 1 and 2.  As a result plexdebrid is refusing to fetch 3, 4, and 5, simply adding them to the retry sequence instead of fetching/adding the single episode release that exist for the episodes.

**Comment by rmkjr** [comment]
Perhaps one solution to both iterations of this, without having to rework the pack and quality filtering too much, could be to process the version preferences before the multi-season pack vs season pack vs episode sorting.  That way versions could filter out results based on user preference, then the built-in sorting and filtering could operate on what results are left.

**Comment by grovolis** [comment]
Any news on this? I have the same problem!

**Comment by itsToggle** [comment]
Hi, this will have been resolved by v2.93. If you only select torrentio and/or orionoid as your scraper sources, PD should now download these single episode releases correctly in one attempt. (to be clear, it should have downloaded the missing episodes in the next attempt 30 minutes later already).

Its generally not advisable to only download single episode releases, as these will over time get fewer and fewer seeders. Only season packs and multi season packs will remain sufficiently seeded and thus available for longer.
