### ISSUE TITLE
Your library seems empty...

### ISSUE THREAD

**Issue by RedCupWhiteLid** [itsToggle/plex_debrid#479]
Hi

I've had this script(s) up and running for a few months now but for some reason its stopped working. When I run the script is get the below.

[15/05/23 15:32:51] [plex] getting plex library section/s "Movies",... done
[15/05/23 15:32:54] [plex error]: couldnt reach local plex library section '12' at server address: http://xxx.xxx.xxx.xxx:32400 - or this library really is empty.
[15/05/23 15:32:54] [plex error]: Your library seems empty. To prevent unwanted behaviour, no further downloads will be started. If your library really is empty, please add at least one media item manually.
[15/05/23 15:32:54] [plex] getting all watchlists ... done

I have tried wiping out allthe config and re configuring to no avail. I have also switched the plex token, changed the plex ip from 127.0.0.1, to lan IP and also localhost with no joy.

Is there a log file I can dig through?

**Comment by igenena** [comment]
> Hi
> 
> 
> 
> I've had this script(s) up and running for a few months now but for some reason its stopped working. When I run the script is get the below.
> 
> 
> 
> [15/05/23 15:32:51] [plex] getting plex library section/s "Movies",... done
> 
> [15/05/23 15:32:54] [plex error]: couldnt reach local plex library section '12' at server address: http://xxx.xxx.xxx.xxx:32400 - or this library really is empty.
> 
> [15/05/23 15:32:54] [plex error]: Your library seems empty. To prevent unwanted behaviour, no further downloads will be started. If your library really is empty, please add at least one media item manually.
> 
> [15/05/23 15:32:54] [plex] getting all watchlists ... done
> 
> 
> 
> I have tried wiping out allthe config and re configuring to no avail. I have also switched the plex token, changed the plex ip from 127.0.0.1, to lan IP and also localhost with no joy.
> 
> 
> 
> Is there a log file I can dig through?
> 
> 

Go to ur movie library on ur browser, check the library number in the url bar, probably it is not 12 anymore, if that's the case, change the library number in the settings of plex debrid script (either using the plex debrid script or in the settings.json, then restart the script)

**Comment by RedCupWhiteLid** [comment]
> If you use RD, you need to add at least one movie in your RD library

The 2 libraries for RD both have content in them...

**Comment by RedCupWhiteLid** [comment]
I've resolved the issue, I had the script to look at a ALL my Plex libraries and 1 of them was indeed empty.... I've removed the empty library and now this is working as expected!
