### ISSUE TITLE
Docker volume lost after reboot

### ISSUE THREAD

**Issue by drkathirpi** [itsToggle/plex_debrid#482]
I created the volume using official method mentioned in the step by step installation page on GitHub

docker plugin install itstoggle/docker-volume-rclone_rd:amd64 args="-v" --alias rclone --grant-all-permissions config=~/rclone/config cache=~/rclone/cache

Then

docker volume create realdebrid -d rclone -o type=realdebrid -o realdebrid-api_key=your-api-key-here -o allow-other=true -o dir-cache-time=10s

And mounted the volume with the containers i like eg. Plex, jellyfin etc

What happen is when reboot the server. Those containers mapped with realdebrid volume not able to start. It throws an error. When i checked the logs of the container. I found out that those containers not able to mount the volume realdebrid

When i list available volumes using docker command, I can't find the volume, so I will run this command

docker volume create realdebrid -d rclone -o type=realdebrid -o realdebrid-api_key=your-api-key-here -o allow-other=true -o dir-cache-time=10s

And the start the containers again. Then everything works perfectly..

This happens every time I reboot.... Any solution???

**Comment by Darrakas** [comment]
Same issue here. This is just a guess, but maybe realdebrid volume is removed because the volume driver is not local, but rclone.
Make a simple script to create the volume and restart containers after that.

**Comment by itsToggle** [comment]
This issue seems to be happening to everyone, and I sadly cant tell you why, as the image is built using the official rclone build settings. The solution does indeed seem to be to write a script that always creates the volume on reboot. Ill look into this a little further but will mark this as completed for now.

**Comment by jbrydges** [comment]
It looks like there is a fix in the official rclone - https://github.com/rclone/rclone/issues/6769
