### ISSUE TITLE
synology nas setup

### ISSUE THREAD

**Issue by red-centre** [itsToggle/plex_debrid#483]
Hi, I'm attempting to get things working on a synology nas - so far I have rclone working as a docker plungin, and the plex-debrid process working, and I am getting source files downloaded to the realddebrid volume - which i can see with the "docker run --rm -i -v=realdebrid:/tmp/myvolume busybox find /tmp/myvolume" command.
What I can't figure out is how to mount the realdebrid volume in the root filing system, or how to make it visible to Plex (which I am running as a synology addin, not through a docker install.

Any suggestions would be much appreciated.

**Comment by cheetah3k5** [comment]
I am having the same issue. Is it working only with the docker version of plex?

**Comment by Richy78** [comment]
> 

Maybe we can help each other. i manage to mount the realdebrid volume but I can't see whats in it when doing "docker run --rm -i -v=realdebrid:/tmp/myvolume busybox find /tmp/myvolume" command.

**Comment by Richy78** [comment]
> > 
> 
> Maybe we can help each other. i manage to mount the realdebrid volume but I can't see whats in it when doing "docker run --rm -i -v=realdebrid:/tmp/myvolume busybox find /tmp/myvolume" command.

Fixed my issue finally (api token issue). If you need help to mount the drive, fist I'll suggest to use portainer.

Let me know if you need extra help

**Comment by itsToggle** [comment]
I assume this has been resolved, correct me if this is still an active issue.

**Comment by Teknoslayer** [comment]
@Richy78 @cheetah3k5 @red-centre 
Are any of you guys able to help me set this up please.
The only thing I got working is the plex_debrid on docker. I cannot get rclone working at all. Always getting some sort of error regardless of what method I try to instal rclond_rd. I have Plex server setup via official synology package and not via docket if that helps

**Comment by joelstitch** [comment]
Any luck with this? I am also trying to get this working on a Synology NAS

**Comment by Teknoslayer** [comment]
No luck as yet, I have reached out to a guy that goes by the name Jesse Bray who knows how to it. He offers a paid service to sort this out.
He’s current busy atm with 2 other orders that he need to attend to and his personal life so hopefully he reaches back out to me soon to sort mine out.
He did say he doesn’t use rclone but uses pdrcrd or pd_zurg instead
I’ve given up based on my abilities so now I’m waiting on him.

**Comment by joelstitch** [comment]
I'll look into it and update if I get it running

**Comment by Richy78** [comment]
> @Richy78 @cheetah3k5 @red-centre Are any of you guys able to help me set this up please. The only thing I got working is the plex_debrid on docker. I cannot get rclone working at all. Always getting some sort of error regardless of what method I try to instal rclond_rd. I have Plex server setup via official synology package and not via docket if that helps

Hi,
sorry for the late reply. I've used Plex on docker. Did you try using that instead of the one on Synology?

**Comment by Richy78** [comment]
> No luck as yet, I have reached out to a guy that goes by the name Jesse Bray who knows how to it. He offers a paid service to sort this out. He’s current busy atm with 2 other orders that he need to attend to and his personal life so hopefully he reaches back out to me soon to sort mine out. He did say he doesn’t use rclone but uses pdrcrd or pd_zurg instead I’ve given up based on my abilities so now I’m waiting on him.

Don't give up man, troubleshooting is the best part! and don't pay, come on

**Comment by Richy78** [comment]
btw chatgpt helped me a lot

**Comment by cheetah3k5** [comment]
> > @Richy78 @cheetah3k5 @red-centre Are any of you guys able to help me set this up please. The only thing I got working is the plex_debrid on docker. I cannot get rclone working at all. Always getting some sort of error regardless of what method I try to instal rclond_rd. I have Plex server setup via official synology package and not via docket if that helps
> 
> Hi, sorry for the late reply. I've used Plex on docker. Did you try using that instead of the one on Synology?

Sorry, I gave up on this a while ago. I haven’t really gotten anywhere

**Comment by Teknoslayer** [comment]
> > @Richy78 @cheetah3k5 @red-centre Are any of you guys able to help me set this up please. The only thing I got working is the plex_debrid on docker. I cannot get rclone working at all. Always getting some sort of error regardless of what method I try to instal rclond_rd. I have Plex server setup via official synology package and not via docket if that helps
> 
> Hi, sorry for the late reply. I've used Plex on docker. Did you try using that instead of the one on Synology?

It’s not Plex that’s given me the issue. It’s rclone for me.
Can’t seem to get it to mount anything. Keeps getting an fuse error.
Plex_debrid actually seems to be operating.
But just cant confirm anything without rclone as that’s meant to link it all up.

**Comment by joelstitch** [comment]
I was able to get it running on my Synology NAS after A LOT of reading and messing around with it. I followed instructions that someone posted on the plex_debrid Discord. Follow these instructions:

```
Still a little more work to do but this should get you 90% of the way to running plex_debrid on synology.

Step 1: Install Docker from the Synology Package Center.

Step 2: Install SynoCli-Disktools from the Package Center.

#Note: Pay attention to the folder structure. If it says /volume1/docker/appdata then that's my folder structure. Please customize it to match your own if needed.

Step 3: Find the latest release of docker-compose by visiting https://github.com/docker/compose/releases and replace the version number in the command below with the latest version.

sudo su
cd /var/packages/Docker/target/usr/bin/
mv docker-compose docker-compose_bak
curl -L https://github.com/docker/compose/releases/download/vX.XX.X/docker-compose-`uname -s`-`uname -m` -o docker-compose
chmod +x docker-compose
sudo docker-compose -v

Step 4: Install rclone as a docker plugin. Source:https://hub.docker.com/r/itstoggle/docker-volume-rclone_rd.

Note: The FUSE driver step is not needed as SynoCli-Disktools has the FUSE driver built-in.

Create the following directories on your host system:

/volume1/docker/appdata/rclone/config
/volume1/docker/appdata/rclone/cache

Then install rclone as a docker plugin:


sudo docker plugin install itstoggle/docker-volume-rclone_rd:amd64 args="-v" --alias rclone --grant-all-permissions config=/volume1/docker/appdata/rclone/config cache=/volume1/docker/appdata/rclone/cache

Copy your RealDebrid API key from https://real-debrid.com/apitoken.

Create a docker volume with the rclone plugin you just installed and name it "realdebrid" using the following command:

sudo docker volume create realdebrid -d rclone -o type=realdebrid -o realdebrid-api_key=APIKEYHEREAPIKEYHEREAPIKEYHERE -o allow-other=true -o dir-cache-time=10s

Step 5: Set up Plex using docker-compose. It is recommended to use Visual Studio Code with the .yml plugin to make editing the code easier. Make sure to use sudo every time you run the command because it makes synology happy. To check if the variables are working, use docker-compose config or docker inspect.

Step 6: Create a hidden .env file and learn how the variables connect between the docker-compose.yml file and the .env file. The .env file must be in the same directory as the docker-compose.yml file.

Create the .env file by running the following commands:

touch .env
nano .env

Inside the .env file, add the following variables :
#Mine is very sloppy right now
PLEX_PORT=32400
PLEX_WEB_TOOLS_PORT=33400
PUID=1026
PGID=100
APPDIR=/volume1/docker/appdata
APPDATA=/volume1/docker/appdata
TZ=America/New_York
USERDIR=/volume1/homes/james
DOCKERDIR=/volume1/docker
DOWNLOADSDIR=/volume1/downloads
DATADIR=/volume1/media/storage
SECRETSDIR=/volume1/docker/secrets
VIDEODIR=/volume1/video
SERVER_IP=
ADGUARD_IP=
LOCAL_NETWORK=
LOCAL_IPS=127.0.0.1/32,10.0.0.0/8,192.168.0.0/16,172.16.0.0/12
Finally, add the following to the docker-compose.yml file:

version: '3.9'
services:
  
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    ports:
      - $PLEX_PORT:32400/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      # - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    devices:
      - /dev/dri:/dev/dri # for hardware transcoding
    environment:
      TZ: $TZ
      HOSTNAME: "sPlex"
      #PLEX_CLAIM: $PLEX_CLAIM
      PLEX_UID: $PUID
      PLEX_GID: $PGID
    volumes:
      - $DOCKERDIR/appdata/plexms:/config
      - $DOWNLOADSDIR:/downloads
      - /dev/shm:/transcode
      - $VIDEODIR:/video
      - realdebrid:/torrents   

volumes:
    realdebrid:
        external: true
```
