### ISSUE TITLE
Orionoid Stream Search Parameter "limitretry" bug

### ISSUE THREAD

**Issue by JackTheTripperr** [itsToggle/plex_debrid#484]
When using the "limitretry" parameter in the plex_debrid settings.json, described in the Orionoid Stream Search API documentation as follows:

> The maximum number of streams to return if the normal search fails. If the filters are too restrictive, no streams are returned. A second search can be conducted without any of the filters and its own link limit. By default this option is disabled.

The following error is returned if no streams are found and the retry parameter comes into effect:

```Python
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jackthetripperr/plex_debrid/scraper/__init__.py", line 46, in multi_scrape
    result[index] = cls.scrape(query, altquery)
  File "/home/jackthetripperr/plex_debrid/scraper/services/orionoid.py", line 120, in scrape
    title = result.file.name.replace(' ','.')
AttributeError: 'NoneType' object has no attribute 'replace'
```

I have next to no development experience, but I think the second scrape by Orionoid is, for some reason, unable to replace '   ' with  ' . ' Maybe due to it's attempt to perform a second search "without any of the filters"? Alternatively, is there something I missed while setting up my Orionoid parameters:

```python
 "Orionoid Scraper Parameters": [
        [
            "limitcount",
            "1000"
        ],
        [
            "access",
            "realdebridtorrent"
        ],
        [
            "sortvalue",
            "best"
        ],
        [
            "streamtype",
            "torrent,usenet,hoster"
        ],
        [
            "protocoltorrent",
            "magnet,http,https,ftp,ftps"
        ],
        [
            "protocolusenet",
            "http,https,ftp,ftps"
        ],
        [
            "protocolhoster",
            "http,https,ftp,ftps"
        ],
        [
            "filesize",
            "75000000_2000000000000"
        ],
        [
            "debridlookup",
            "user"
        ],
        [
            "metarelease",
            "bdrip,bdrmx,bdscr,bluray,dvd,dvdrip,dvdrmx,dvdscr,hdts,hdrip,hdtv,pdvd,ppv,scr,ts,tvrip,webcap,webdl,webrip"
        ],
        [
            "videoquality",
            "scr,scr720,scr1080,sd,hd720,hd1080,hd2k,hd4k"
        ],
        [
            "video3d",
            "false"
        ],
        [
            "audiochannels",
            "2_8"
        ],
        [
            "audiolanguages",
            "en"
        ],
        [
            "limitretry",
            "500"
        ],
        [
            "filename",
            "true"
        ]
    ],
```
Thanks in advance and apologies if this is a laughable display of ignorance. In the meantime, I will go pet my dog who hasn't shown any awareness of my slim knowledge base for this kind of thing (or at least, she pretends not to notice).

**Comment by itsToggle** [comment]
that should fix the crash, but Im unsure if the underlying issue will be fixed. Ill close this for now to clean up.
