### ISSUE TITLE
[plex error]: could not reach plex

### ISSUE THREAD

**Issue by Helssiv** [itsToggle/plex_debrid#485]
https://discord.com/channels/1021692389368283158/1021692389812871169/1113182025441083463

plexdebrid spits all 6 seconds the error "[plex error]: could not reach plex".

I cant find any networking issues and else all seems to work just fine.

**Comment by Crackvignoule** [comment]
Same

**Comment by itsToggle** [comment]
alright this should be fixed by #81b9f1c
