### ISSUE TITLE
Overseerr (Jellyseerr) request marking doesn't work correctly

### ISSUE THREAD

**Issue by Darrakas** [itsToggle/plex_debrid#486]
Either I have something wrong with my setup or its a bug, but when requesting a movie or show, plex_debrid does its job fine until it is supposed to make the request available. It adds the show to my Jellyfin library but never marks it ready in Jellyseerr until I manually run the job "Jellyfin Recently Added Scan".

Logs from plex_debrid:
[31/05/23 12:53:07] jellyfin error: b''
[31/05/23 12:53:07] jellyfin error: (json exception): Expecting value: line 1 column 1 (char 0)
[31/05/23 12:53:07] [overserr] marking request as available
[31/05/23 12:53:08] [overseerr] error: b'{"message":"Media does not exist."}'

Maybe there should be some sort of delay to check Jellyfin library, because the requested media is added there.

For now, I changed the Jellyseerr to scan recently added library every 30 seconds, but thats just a quick band aid and is not the best solution.

There is also error with jellyfin, no matter if I do fresh install, it still gives it. I have debug set to true in plex_debrid and that's all it gives.

**Comment by itsToggle** [comment]
related to existing issue https://github.com/itsToggle/plex_debrid/issues/423
