### ISSUE TITLE
Server IP works fine for Library Collection but fails to connect when using same IP for Library Update Services

### ISSUE THREAD

**Issue by IniNew** [itsToggle/plex_debrid#489]
Setting up for the first time and running into an issue connecting to the server for Library Update Services.

I have assigned a static IP to the machine running the Plex Media Service. I have forwarded port 32400. 

I am able to connect to the server remotely, using a separate machine. 

When setting up plex_debrid for the first time, I am using a basic Plex only setup (selecting 1 from the options). 

The static IP address I've set works for connecting to Library Collection Services just fine, but when I use the same IP address for the Library Update Services, I get the error: 

`It looks like your plex server could not be reached at [ip address]:32400. Make sure that plex media server is running, that you have claimed the server and that you have created at least one plex library.`

I have verified that I have "claimed" the server under my Plex account. 

I have created the 'Movies' and 'Shows' libraries on the virtual mounted drives located under X:\ and I do see those libraries in my Plex Server.

Any thoughts on what I might be doing wrong here?

**Comment by IniNew** [comment]
Looks like the problem is the empty media libraries bug that is listed under the Plex limitations section towards the bottom. Going to populate it with a single file then see what I can figure out.

**Comment by IniNew** [comment]
Ok. I've tried just about everything I can come up with to get a simple file into my rclone X:\ library, and cannot for the life of me get it to work. The library is currently empty. 

I tried the copyto command, but got a kickback for the sizes not matching. I used the --ignore-size attribute and then it said it couldn't read the metadata. 

Is there another solution here?

**Comment by piratsch** [comment]
Does the file also show up in Plex?
I suggest you add one movie and one show, make sure Plex picks those up and then try again.

**Comment by kevzz01** [comment]
Were you able to figure it out? I am having the same problem. The shows and movies does show up in my mounted X drive.

**Comment by piratsch** [comment]
> Were you able to figure it out? I am having the same problem. The shows and movies does show up in my mounted X drive but not in the plex. Plex actually downloaded one file for some reason but that's all I get.

First of all, Plex doesn't download anything by itself. Plex is only a media server that lets you access media on your drive(s).
You are mixing a few problems together.

Before anything else, you need to figure out why Plex doesn't show the content in your mounted drive.

Check [this link](https://support.plex.tv/articles/200288926-creating-libraries/) to see how you can set the media location for your libraries.

**Comment by kevzz01** [comment]
> > Were you able to figure it out? I am having the same problem. The shows and movies does show up in my mounted X drive but not in the plex. Plex actually downloaded one file for some reason but that's all I get.
> 
> First of all, Plex doesn't download anything by itself. Plex is only a media server that lets you access media on your drive(s). You are mixing a few problems together.
> 
> Before anything else, you need to figure out why Plex doesn't show the content in your mounted drive.
> 
> Check [this link](https://support.plex.tv/articles/200288926-creating-libraries/) to see how you can set the media location for your libraries.

I got it to work. I edited settings.json and put http instead of https for localhost. I believe I tried the same thing through powershell but it will write https regardless.

**Comment by IniNew** [comment]
> 

Plex *does* show content in my mounted library. Library update services however, does not connect. I was able to get a hacky version to work using a UTC path, Sonarr, Radarr, and RDTClient, but still can't get Plex_debrid to connect during the Library Update Services setting.

**Comment by IniNew** [comment]
After making sure there were files in both X:\shows and X:\movies, syncing the libraries again, it appears to be working. Trick seems to be making sure that is stuff in any libraries you have set up in Plex.

**Comment by itsToggle** [comment]
yeah thats it, this should be made clearer in the readme.
