### ISSUE TITLE
Cannot get rid of a movie

### ISSUE THREAD

**Issue by Spectre216** [itsToggle/plex_debrid#490]
So during testing I added a movie, and it downloaded and I could play it fine. However, after removing it from my Watchlist and deleting it in Plex, the file just keeps coming back. If I remove it from my folders manually, it breaks the whole thing and I can't get anything downloaded until I redo the mount to a new folder. Any thoughts on what might be going on? I don't see any error messages in my terminals, so I don't know what is causing it to keep coming back over and over again.

The real weird thing is that it is only this specific movie. Anything else I've tried I can delete just fine. 

Any thoughts?

Plex Server: Ubuntu 22.04 VM with XFCE desktop

**Comment by piratsch** [comment]
Delete it from your debrid service.

**Comment by itsToggle** [comment]
Im assuming this issue has resolved itself in order to clean up. correct me if thats not the case.
