### ISSUE TITLE
Search behavior for in season tv shows with multiple releases

### ISSUE THREAD

**Issue by joshali1990** [itsToggle/plex_debrid#496]
I noticed that plex_debrid searches for SXE01 when looking for ongoing seasons that have multiple episodes released using torrentio. For example today I added Nancy Drew and during the first scrape attempt it searched for S04, but since torrentio needs a episode number, it only found episode 1. During the next scrape attempt it correctly searched for E04E2 and S04E3. Can you change the search behavior to always search by episode for in season tv shows?

**Comment by itsToggle** [comment]
so the issue was that it only downloaded E1 in the first attempt and not the other episodes? Or did I missread the issue?

**Comment by joshali1990** [comment]
Yes that is correct. The current behavior is to scrape by season if there are more than 2 episodes missing. This works fine with Jackett, but with Torrentio only the first episode is found since it scrapes for S0XE01.
