### ISSUE TITLE
Plex_debrid with managed users

### ISSUE THREAD

**Issue by MaitreKuc** [itsToggle/plex_debrid#501]
Hi,

First I want to say thank you for this program that works really well.

I know that Plex_Debrid can't see the "Watchlist" for managed users, because they don't have access to it.
But after inspecting the source code at the "Discover" option in the Plex Web settings, I wanted to try a manipulation.
So I changed the value of the "includeDiscoverSource" ID from "opt_out" to "opt_in" and then saved the changes.
I was pretty sure it wasn't going to work, but weirdly it works, I have access to "Watchlist" and "Discover" from my managed users (Plex web, Plex android and Plex Android TV works)

I put a post on the plex forum if you want the process:
https://forums.plex.tv/t/add-discover-to-managed-users/794138/38?u=maitrekuc

So since the "Watchlist" works for managed users (admittedly it's not official), there wouldn't be a way to force Plex_Debrid to scan all "Watchlists"? Or I failed to make it work properly.

**Comment by itsToggle** [comment]
Haha that's awesome!! I'm sure there is a way for PD to monitor these watchlists as well, since managed users do have a unique Plex token. Have you tried adding your managed users into PD?

**Comment by MaitreKuc** [comment]
According to another github repository (https://github.com/jacobgillespie/plex-sync/issues/57), managed users don't have tokens, but according to this reddit it should be possible. (https://www.reddit.com/r/PleX/comments/rm97b2/comment/hrye8zs/)
So I just tried, but I get an error.

![image](https://github.com/itsToggle/plex_debrid/assets/30301747/a4c53ca6-5e3c-412a-b857-07c7ab6b8373)
