### ISSUE TITLE
Permission Issue

### ISSUE THREAD

**Issue by dikkatdeli** [itsToggle/plex_debrid#505]
Hi,

I created /root/torrents folder and my debrid config name is "almanya-remote"

I run this:

./rclone-linux mount almanya-remote: /root/torrents --dir-cache-time 10s --allow-other

After that I try to set up plex folders but permission does not change while rclone working so I can't add media library

chown -R plex: torrents/

root@linux-server:~/torrents# ll
total 4
drwxr-xr-x  1 root root    0 Jul 15 20:02 ./
drwx------ 10 root root 4096 Jul 15 19:42 ../
drwxr-xr-x  1 root root    0 Jul 15 20:02 history/
drwxr-xr-x  1 root root    0 Jul 15 20:02 links/
drwxr-xr-x  1 root root    0 Jul 15 20:02 magnets/

**Comment by itsToggle** [comment]
have you tried adding the "umask" flag? https://rclone.org/commands/rclone_mount/ search for "umask"
