### ISSUE TITLE
Trakt API Key Issue

### ISSUE THREAD

**Issue by ccs46** [itsToggle/plex_debrid#507]
![Plex Debrid Trakt API Issue](https://github.com/itsToggle/plex_debrid/assets/29940132/6f878a80-e2c8-4a5b-b569-b80783455ac5)
Contacted trakt and they said that this 401 error I'm getting says it's not authorized, but I've reauthorized plex_debrid several times and gave it a new API key for my trakt user and I still get this issue.

Trakt lists the 401 error as being 401	Unauthorized - OAuth must be provided

**Comment by itsToggle** [comment]
hm is this issue persisting? It seems to work for me.

**Comment by ccs46** [comment]
> hm is this issue persisting? It seems to work for me.

Hi Toggle,

Unfortunately yes it is. My buddy's instance is doing it as well and we're not sure why.

**Comment by ccs46** [comment]
<img width="1257" alt="image" src="https://github.com/itsToggle/plex_debrid/assets/29940132/1cb3c317-29c5-474a-96cd-3376946776aa">
It's been deauthorized and reauthorized. Based on some Googling it looks like this can be caused by it not sending OAuth with the API calls its doing.

**Comment by ccs46** [comment]
@itsToggle Did you have any thoughts on this? Trakt keeps referring us back to you as they said it's an oauth issue with plex_debrid

**Comment by ccs46** [comment]
This issue was fixed by deleting the settings.json file and starting fresh with a new API key from trakt.

**Comment by ccs46** [comment]
This issue was fixed by deleting the settings.json file and starting fresh with a new API key from trakt.
