### ISSUE TITLE
Automation Idea

### ISSUE THREAD

**Issue by Reffler** [itsToggle/plex_debrid#51]
Firstly, I would like to say I am so thankful you are developing this tool! It really is all I needed and it helps me a lot!

Secondly, I would like to request a quality of life feature.

When an user wishes to watch a title, the following process occurs:

1. Choosing the desired title;
2. Adding the title to the Wishlist;
3. Going Back to the home page waiting for the title to appear;
4. Clicking on the title once again

I believe the user experience would be positively impacted if steps 3 and 4 were somehow automated. That way when  clicking on the "Add to Wishlist" button, the selected title would automatically open and play in the video player after a few seconds.

**Comment by itsToggle** [comment]
Hey! That's a great idea. 

Sadly, we are very limited in the ways we can interact with plex, and an automated redirect when clicking "add to watchlist" is not an option. One could write a browser plugin that is capable of such an automation, but that would mean it will only work when using Plex through a browser and not through the various apps for android/tv/etc.

I'm currently working on a side project (short video on the bottom of the readme), that allows for a deeper integration into plex by mocking a Plex server. But even with this deeper integration, I have not managed to get plex to directly open the newly downloaded content. I am working on it though.
