### ISSUE TITLE
Docker instalation with rclone_rd included 

### ISSUE THREAD

**Issue by humbertogontijo** [itsToggle/plex_debrid#512]
Hey, first of all, thank you for this repository
Is it possible to create a docker image that runs a script to setup rclone_rd within it(the first time)? This way it would only be necessary to setup plex itself. And this could run in a single image
And further more we could wrap this docker image in an addon for those like me that have a pi running hassio(Home assistant OS)

**Comment by itsToggle** [comment]
Im not entirely sure, but there is a combined docker image for plex_debrid and rclone_rd which has some scripting in it. I havent followed it too closely, but check out: https://github.com/I-am-PUID-0/pdrcrd for more info!
