### ISSUE TITLE
Not scraping content

### ISSUE THREAD

**Issue by amcgready** [itsToggle/plex_debrid#514]
I'm running into a weird issue with media scraping. Plex debrid checks my watchlist correctly and correctly identifies the item in the watchlist, but it never scraps any of the scraper sources that are setup. Is there something I am potentially missing? I feel like I've gone thru the settings a few times and I'm stumped.

**Comment by itsToggle** [comment]
I assume this was fixed. If not, hop on the discord server and ask the community:)
