### ISSUE TITLE
docker unable to connect to localhost

### ISSUE THREAD

**Issue by iamrk73** [itsToggle/plex_debrid#52]
hi just trying out the dockerized version of plex debrid unable to get it to work
after the initial setup when i choose run it says unable to connect to localhost:32400 or the plex library is really empty

**Comment by itsToggle** [comment]
Sounds like either plex is not reachable under that address (which is unlikely) or your plex library is empty. 

From the Readme's Limitations section:

> plex_debrid cannot destinguish between a truly empty library and a library that couldnt be reached because its offline (or not reachable for any other reason). In order to avoid unwanted behaviour, the script simply stops running whenever an empty library is encountered. You will need to manually add at least one media item to the libraries visible by plex_debrid, before the download automation can run savely.

You need to add at least one torrent to your debrid service manually, or add a locally downloaded movie/show.

**Comment by beljim** [comment]
Try replacing localhost with the iP address of the docker machine.

**Comment by iamrk73** [comment]
Hi the library is not empty  it has many files in it the non dockerized version works picks up plex library  very well . how can I replace localhost with ip of host machine ? 🤔

**Comment by itsToggle** [comment]
navigate to "/Settings/Content Services/Plex/Plex server adress"

**Comment by itsToggle** [comment]
Im assuming you were able to solve this and will close the issue. Feel free to comment if you are still having this problem :)

**Comment by iamrk73** [comment]
Hi sorry was just lost in some work related stuff yes will definitely give this a try and should solve the issue
