### ISSUE TITLE
Download uncached or lower resolution file if basic option not available?

### ISSUE THREAD

**Issue by Danferno** [itsToggle/plex_debrid#522]
Is there a way to set up the script such that it tries to download an uncached or lower resolution file if the basic option (1080p sdr) is not available?

**Comment by itsToggle** [comment]
Yes. The readme details this, just set up your versions accordingly.
Simply make the following changes:
```
1) cache status preference cached
2) resolution preference highest
3) resolution requirement <= 1080
```
