### ISSUE TITLE
Jellyfin or Jellyseerr Support?

### ISSUE THREAD

**Issue by HashaRock** [itsToggle/plex_debrid#53]
hey itsToggle!

I just wanted to ask about Jellyfin compatibility since Jellyfin is FOSS and runs quite similarly to Plex.
At the moment, I can use plex_debrid to get the files and then use Jellyfin to play them, but I'd rather get rid of the middle man and simply use Jellyfin, Jellyseerr [https://hub.docker.com/r/fallenbagel/jellyseerr], and plex_debrid. I don't care as much for the Plex reccommended section but I would love to have Jellyfin support!

Thanks so much for your great work on this cohesive software!

**Comment by roembol2000** [comment]
The readme says that Overseerr is supported. Since Jellyseerr is after all a fork of Overseerr, I would say the chances of it simply just working are quite high. I am currently setting this up for myself to see how this would work.

**Comment by itsToggle** [comment]
Hey :) jellyseerr should work as far as i can tell, but the script is currently written around the plex media type. It relies on your Plex servers library to determine what's already downloaded and gathers other media information from the plex metadata api. So at the moment you will need to run your Plex server in the background. But you can get around using plex discover to add content by Integrating trakt, overseerr or perhaps jellyseer.

I am currently rewriting that plex integration though. I've been asked by multiple users to detach this script from plex, so in the near future you will be able to choose which content service (plex, trakt, and perhaps overseerr and jellyfin) should be used to determine your current media collection. This will allow for a setup that doesnt involve plex at all.

**Comment by HashaRock** [comment]
Makes sense, I think its better to run it stock at the moment until more support is brought in. Overseerr can work as normal and Plex will run in the background while Jellyfin actually plays the content!

Thanks so much for your work on this.

**Comment by itsToggle** [comment]
I'll comment here if I finish the above mentioned changes :)

**Comment by itsToggle** [comment]
Hey! plex_debrid now has an experimental branch which allows you to run the entire download automation through trakt.tv and not plex :) I will add further updates to the experimental branch like a jellyfin and emby library refresh after a sucessful download, and if all seems stable I will pull these changes to the main branch. Feel free to check out the experimental version aswell though.
