### ISSUE TITLE
Exit from search loop without waiting for completion

### ISSUE THREAD

**Issue by maxexcloo** [itsToggle/plex_debrid#533]
Wondering if there's a way to make the exit command not have to wait for the loop (I always end up having to exit, edit config to enable the menu and then start it again to get out) - maybe a different command that kills all and dumps to the menu?

**Comment by BEisem** [comment]
Yes please!

**Comment by jonquilcityboy** [comment]
I'm stuck in a loop right now, can you explain how to edit the config to enable the menu?
