### ISSUE TITLE
Sort releases by the number of seeders

### ISSUE THREAD

**Issue by Jaxenormus** [itsToggle/plex_debrid#54]
First off I want to say this is a great scripts and is quite use-full but I have ran into the issue of the script picking torrents with 1 or 2 seeders hence it taking a while to download my movies. I have Jackett setup and when I manually search for a movie it brings up multiple torrents with tons of seeders so I'm left to assume its something to do with the script

**Comment by itsToggle** [comment]
Hey, the script currently doesn't sort by seeders as the main goal is to download debrid cached releases. I will add the option to sort by seeders in the next commit, thanks for the suggestion!

**Comment by Jaxenormus** [comment]
No problem in that case it might be due to the fact that I am using put.io which I don't think supports debrid cached release iirc, I'll test out realdebrid and see if I have the same issue

**Comment by itsToggle** [comment]
Yeah that's sadly correct, put.io has no api method to check which scraped releases are cached before adding them to put.io.

In my testing, I've had the best results with realdebrid. They seem to have the most cached releases for the torrent indexers im using - but you will most likely always find at least one cached release if you choose any debrid service other than put.io :)

**Comment by itsToggle** [comment]
You can now sort releases by the number of seeders. 

If you do a fresh install of plex_debrid, a sorting rule to prefer larger amounts of seeders is added by default. 

If you have an existing "settings.json" file, you will need to add the sorting rule yourself. Check the readme for a description on how to sort by seeders :)
