### ISSUE TITLE
Items added to ignore list after release

### ISSUE THREAD

**Issue by joshali1990** [itsToggle/plex_debrid#55]
Is there a way to delay adding items to the ignore list if nothing is found?  Sometimes new episodes are scraped right after release, but before a torrent is found and are added to the ignore list. When the torrents are available a few hours later, it doesn't re-scrape. Maybe an option to add a 24 hr delay before adding to the ignore list?

**Comment by itsToggle** [comment]
Thats a good idea! I can have plex_debrid checking the item every 30 minutes until some retry maximum of 12 (so 6h) or something. Im currently working on a larger feature for the script, but I should get around to implementing this in the next week or two.

**Comment by itsToggle** [comment]
plex_debrid will now attemp to download a movie/episode 6 times in 30 min intervals (so 3 hours) before its ignored. Testing will reveal if this is enough time, I might increase the number of attempts later on.
