### ISSUE TITLE
[Help] ANIMATION MOVIES AN SHOWS

### ISSUE THREAD

**Issue by Beoriginalpt** [itsToggle/plex_debrid#585]
So i'm wondering if there is any way to make the debrid chose audio languages (doubled versions) of moveis and shows for my kids.

Hope i'm make any silly question so thanks in advance guys 😊

**Comment by Beoriginalpt** [comment]
never mind i thing i've figured it out ...

**Comment by pranavkafle** [comment]
@Beoriginalpt , could you please share how you managed to figure it out? I am trying to get shows that have dual audio, one in English and one in Hindi. I plan to let Plex show the options for the movie and then the users can choose which one to play? Have you set it up similarly?

**Comment by Beoriginalpt** [comment]
> @Beoriginalpt , could you please share how you managed to figure it out? I am trying to get shows that have dual audio, one in English and one in Hindi. I plan to let Plex show the options for the movie and then the users can choose which one to play? Have you set it up similarly?

Not quite. I created a seperated path in debrid and a new scraper option to try to scrap the content in my language fairly simple approach it only doubles "drives" i have one for english and the other one
