### ISSUE TITLE
Request: Add support for other debrid providers

### ISSUE THREAD

**Issue by morpheasgr** [itsToggle/plex_debrid#6]
Hi, would love to see your projects evolve and support other Debrid providers which offer API access.

Can help test, and maybe implement and can also provide temporary API keys from my accounts for the following services: Debrid-Link.fr, AllDebrid.com.

Contact me on Discord: Morpheas_GR#6295

I bet many people would also want to see this for Premiumize.me

Links to API:
DL: https://debrid-link.fr/api_doc/v2/introduction

AD:
https://docs.alldebrid.com/#general-informations

Both these services offer Webdav by the way, in contrast to RD and Debrid-Link.fr also seeds content which makes it my current favorite and compatible with private trackers.

Let's chat if you want :)

**Comment by itsToggle** [comment]
Hey, Ive now prepared this script to allow the Integration of different debrid providers. Before actually implementing any of them I will clean up the code a bit. 

I will most likely add support for premiumize first, since Ive worked with their API before and there is an existing rclone implementation for it. 

I cant code and maintain an rclone implementation for all debrid providers.

Have you tried integrating the Webdav servers of these other providers into Plex? I was under the Impression that any WebDav server (at least on windows) has a filesize limit of 50mb, so you cant watch movies. If that isnt the case and the webdav servers work nicely with Plex, I would only have to integrate them into this download automation which should be easy enough.

**Comment by morpheasgr** [comment]
The webdav is only meant for read-only access to files/folders. The webdav entry points are on their servers and not on the LAN. I just added a 100GB file to my cloud to test. My file manager on Android where I have mounted their Webdav was able to read/stream the video file perfectly (I selected 'Direct Link' when opening, not 'save in temp'. MX Player Pro was able to play it back without much stuttering. It's basically a mock webdav. Deletions have to be done via the API.

I like your project's approach that you are trying to eliminate the downloading necessity that is associated with Plex. My vision is to take this a step further and eliminate the PC from the equation somehow, run/mock a Plex Server and port everything else needed to Android devices.

I am a huge anime fan by the way, but this can be extended with additional scrapers.

**Comment by itsToggle** [comment]
Premiumize and Alldebrid added :) I will try to get Debrid-Link working aswell. Does Debrid-Link support cached torrent releases?

**Comment by morpheasgr** [comment]
> Does Debrid-Link support cached torrent releases?

Hell yeah :)

**Comment by itsToggle** [comment]
Ah nice, okay! Cool service. I only have a 'free' account, and when I added a relatively popular release it had to download first. I should be able to get this implemented today or the day after :)

**Comment by itsToggle** [comment]
Okay Im at my daily limit on my free debrid link account, could you try out if my implementation works?

I sadly couldnt get the oauth authentification via device code to work. Eventhough it returned an api_key, Im getting an 'access_denied' error when using it. So for now, you have to enter your private api key.

**Comment by morpheasgr** [comment]
Wait wait. Don't close this yet. Wanted to reply sooner, but I've been meaning to ask for a private way to contact you. Discord, Telegram, whatevs. I want to give you a voucher for free premium days, I've been talking a lot to their development team and they had told me to let them know if I need a voucher for devs.

**Comment by itsToggle** [comment]
finally got around to fixing some of the debridlink issues in the latest release. The guys over on debridlink.fr gave me a whole freakin year of premium! I might need to switch to debridlink alltogether haha

**Comment by morpheasgr** [comment]
They are super awesome :) most caring and friendly debrid service in the world.
