### ISSUE TITLE
[feature request] Please add a flag so that it runs in the background without the menu

### ISSUE THREAD

**Issue by toneman77** [itsToggle/plex_debrid#611]
Right now I'm running plex_debrid in a docker-compose together with jellyfin. If I want to change some settings I:
- edit the settings.json and change `"Show Menu on Startup"` to `"true"`
- start a temp container interactively
- change stuff with the menu and exit
- edit the settings.json and change the setting back to "false" because only then it actually runs without my intervention via docker
- docker-compose restart the plex_debrid container

This is a bit cumbersome which could be mitigated easily with a flag or env variable in the container. Let's say if main.py would accept a `--daemon-mode` then the menu wouldn't pop up and just run. So if I run the container like before (to keep backwards compatibility) the menu pops up, but if I start the container in my compose file with the flag it just runs in the background as if the setting in the json was set to "false"

**Comment by joelstitch** [comment]
Can you explain a little better how to run the script without the menu? I would like to run a script at startup that starts the service without the need of the menu.

**Comment by toneman77** [comment]
@joelstitch, open the settings.json (it's just a text file) and set the option "Show Menu on Startup" to "false" then it wont show the menu and "just run"

**Comment by remmycat** [comment]
I saw in the source code that there is already a flag, it's `-service` (yeah, just one dash), which you can use instead of the persisted setting.

**Comment by toneman77** [comment]
@remmycat you just saved my day. It works! and then shows in stdout:

`"Running in service mode, user input not supported."`

Thanks.
Can be closed

**Comment by joelstitch** [comment]
> I saw in the source code that there is already a flag, it's `-service` (yeah, just one dash), which you can use instead of the persisted setting.

How would I use that, I just tried running the command with -service and I just get errors.

**docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "-service": executable file not found in $PATH: unknown.
ERRO[0011] error waiting for container: context canceled**

**Comment by joelstitch** [comment]
> @joelstitch, open the settings.json (it's just a text file) and set the option "Show Menu on Startup" to "false" then it wont show the menu and "just run"

I can't find the file settings.json anywhere.

**Comment by toneman77** [comment]
> > @joelstitch, open the settings.json (it's just a text file) and set the option "Show Menu on Startup" to "false" then it wont show the menu and "just run"
> 
> I can't find the file settings.json anywhere.

in my docker-compose.yml:
```
...
    plex_debrid:
        image: itstoggle/plex_debrid
        container_name: 'plex_debrid'
        volumes:
            - /path/to/plex_debrid/config:/config
        restart: always
        command: "python ./main.py --config-dir config -e TERM=xterm -service"
        network_mode: host
...
```
regarding the settings.json: for me it's wherever you mapped the /config folder to. In my example above: /path/to/plex_debrid/config
