### ISSUE TITLE
Reset to default 

### ISSUE THREAD

**Issue by Bayharbourbutcher1** [itsToggle/plex_debrid#62]
Hi mate, thanks for creating this wonderful tool. Is there a way to reset all the settings of the script to default? I was playing with scrapers/sort releases etc and would like to know how to reset it back to default. Thanks again.

**Comment by itsToggle** [comment]
Hey, you can simply rename the settings.json file :) restarting the script will then guide you through the initial setup again, so open up your old settings and just copy/paste the values.

**Comment by Bayharbourbutcher1** [comment]
Fantastic! Easy as, that makes sense, thanks again.
