### ISSUE TITLE
Quality Filters to be used while scraping

### ISSUE THREAD

**Issue by dspdhckr** [itsToggle/plex_debrid#66]
If we can set the quality filter like the minimum the scraper can fetch is 720p and maximum 1080p or 1440p in the filter would be great instead of filters based on sizes. Size filter is not useful in the cases where episodes with variable duration will vary in sizes too, effectively meaning missing out on those one.

**Comment by itsToggle** [comment]
Check the readme again, you can sort releases by completely customizable rules :)

**Comment by dspdhckr** [comment]
Ohh well yeah. Thanks. Will go with the documentation wise rules. Thanks :)
