### ISSUE TITLE
Script not working at all for last two months

### ISSUE THREAD

**Issue by ghost** [itsToggle/plex_debrid#660]
The script is not working at all for me. I have re-cloned the repository and clean installed it. Still its not working and finding torrents at all. I removed and cleared whole of my Trakt watchlist and removed users too. Please see the below screenshot. For new movies, old movies this is happening. Anyone please help? 

<img width="1506" alt="Screenshot 2024-03-07 at 19 50 06" src="https://github.com/itsToggle/plex_debrid/assets/132819104/a1c4b728-195b-4278-b014-5c73b853cf5c">

**Comment by subvhome** [comment]
Yea this is also happening to me. Looks like it is searching against streamio and not getting hits. Oddly enough, it is searching for the title string and playing around with the release year. never recalled this. This happened recently as there are new content in my plex.. just not sure what is getting stuck

**Comment by subvhome** [comment]
> The script is not working at all for me. I have re-cloned the repository and clean installed it. Still its not working and finding torrents at all. I removed and cleared whole of my Trakt watchlist and removed users too. Please see the below screenshot. For new movies, old movies this is happening. Anyone please help? 
> 
> <img width="1506" alt="Screenshot 2024-03-07 at 19 50 06" src="https://github.com/itsToggle/plex_debrid/assets/132819104/a1c4b728-195b-4278-b014-5c73b853cf5c">
> 

I had the same thing.  Just found out the culprit.  Is it safe to assume you've created a vps and installed this in a reverse proxy or created a VPN tunnel on the plex server? I did and the vps did not like torrentio. I need to reconfigure my wireguard

**Comment by ghost** [comment]
Yes you are correct. I have set it up on a VPS and Cloudflare Tunnel and Tailscale installed. I have removed both the software and rebooted my VPS, still its not working. How do I resolve it?

**Comment by subvhome** [comment]
You need to do some research on how to ensure that only plex traffic is tunneled through the vpn. I'm not 100% of your setup. 

Would it be possible for you to share what your setup is like? Here is mine.

I have two servers. One local that runs PMS & plex_debrid. This has IP address of 192.168.1.100.  Another server using OCI VPS that is used as a VPN server and a reverse proxy that connects back to local network. This has a public ip address that i won't disclose.

Tunneling the two servers (both linux) is wireguard. Nginx is used for the reverse proxy.  With a plain VPN tunnel estabilshed, all traffic from my local server was being tunneled to the VPS which essentially used the VPS gateway to route traffic to the internet. The VPS didn't like torrentio traffic, which caused no results when scraping. 

I configured the VPN from the client side (my local network) to only allow traffic from my local address to route to the tunnel ip address: `PostUp = ip route add 192.168.1.100/32 via 10.66.66.1 dev wg0`

This is what resolved it for me. I then made sure the firewalls were all persistent and now when I run `curl -4 ifconfig.me` from my local server, my public address is that of my ISP and when I do the same on the VPS server, the VPS public address is returned.

I am not sure how to configure cloudflare for this. I don't mind helping.

**Comment by TheDomovoi** [comment]
Probably not the same issue since I see you're using torrentio already, but I came across this while having problems with my setup. Turns out it was the two default scrapers not finding anything. I removed rarbg and added torrentio and things started scraping properly again.

**Comment by ghost** [comment]
@subvhome I am using my Plex Server on OCI and then on that I do not have Firewall and IPtables set. Apart from that, no Cloudflare Tunnels or Tailscale. I have by the way, ControlD installed through their Terminal CLI. I checked the logs through ControlD and they are showing that it is resolving properly.  @TheDomovoi I am not using two separate sources. I only have Stremio as a source.

**Comment by subvhome** [comment]
For me OCI is my VPS and they don't like torrentio traffic I was sending. So I left that traffic on my local server

**Comment by ghost** [comment]
It was allowing me earlier. Only since last October I guess I am facing this issue. How about if I encrypt my connection using Cloudflare Zero Trust Argo Tunnels? Also, is there any workaround if I want to run this script 24*7 on any other free services?

**Comment by bsmithio** [comment]
Are you running this on a vps? Realdebrid and Alldebrid are blocking datacenter IPs. Realdebrid started this about 10 months ago or so. You'll need to get a VPN that works with Realdebrid or Alldebrid for the plex_debrid container. They should have a list of VPNs that work with them on their websites. I used Windscribe and https://github.com/jordanpotter/docker-wireguard and attached the wireguard container network to the plex_debrid container. Once I ran plex_debrid with the VPN I got torrentio results. 

> For me OCI is my VPS and they don't like torrentio traffic I was sending. So I left that traffic on my local server

It's not Oracle that is blocking torrentio, it's Alldebrid or Realdebrid blocking the Oracle IP.



Here is my setup.

Wireguard Container
`sudo docker run --name wireguard --cap-add NET_ADMIN --cap-add SYS_MODULE --sysctl net.ipv4.conf.all.src_valid_mark=1 -v ./wg0.conf:/etc/wireguard/wg0.conf -e LOCAL_SUBNETS=10.0.0.0/24 jordanpotter/wireguard` 

LOCAL_SUBNETS allows you to give wireguard and plex_debrid containers access to your local network. Define as accordingly to your local subnet. 

Plex Debrid Container
`sudo docker run -v /path/to/config:/config --net=container:wireguard -ti itstoggle/plex_debrid`

**Comment by subvhome** [comment]
> Are you running this on a vps? Realdebrid and Alldebrid are blocking datacenter IPs. Realdebrid started this about 10 months ago or so. You'll need to get a VPN that works with Realdebrid or Alldebrid for the plex_debrid container. They should have a list of VPNs that work with them on their websites. I used Windscribe and https://github.com/jordanpotter/docker-wireguard and attached the wireguard container network to the plex_debrid container. Once I ran plex_debrid with the VPN I got torrentio results. 
> 
> > For me OCI is my VPS and they don't like torrentio traffic I was sending. So I left that traffic on my local server
> 
> It's not Oracle that is blocking torrentio, it's alldebrid or realdebrid blocking the oracle IP.
> 
> 
> 
> Here is my setup.
> 
> Wireguard Container
> `sudo docker run --name wireguard --cap-add NET_ADMIN --cap-add SYS_MODULE --sysctl net.ipv4.conf.all.src_valid_mark=1 -v ./wg0.conf:/etc/wireguard/wg0.conf -e LOCAL_SUBNETS=10.0.0.0/24 jordanpotter/wireguard` 
> 
> LOCAL_SUBNETS allows you to give wireguard and plex_debrid containers access to your local network. Define as accordingly to your local subnet. 
> 
> Plex Debrid Container
> `sudo docker run -v /path/to/config:/config --net=container:wireguard -ti itstoggle/plex_debrid`

This makes more sense. The rules for my setup  allows rd traffic to remain on my local network. Thanks for clarifying

**Comment by bsmithio** [comment]
ProtonVPN may be a good free alternative for anyone looking into this since they give you an unlimited plan for 1 device and are on the Realdebrid list of approved VPNs. 

Just create a ProtonVPN account and choose the free plan, on the Downloads tab scroll all the way down to generate a wireguard config, that's what you would use for the wireguard container.

One could also host a wireguard server on their local network and create a peer config for the wireguard container.
