### ISSUE TITLE
Unable to get Trakt added

### ISSUE THREAD

**Issue by weiseman66** [itsToggle/plex_debrid#669]
### Discussed in https://github.com/itsToggle/plex_debrid/discussions/668

<div type='discussions-op-text'>

<sup>Originally posted by **weiseman66** April  4, 2024</sup>
When I try to add my Trakt User I get: 
[04/04/24 11:34:44] [trakt] error: (401 unauthorized): trakt api key for user '' does not seem to work. Consider re-authorizing plex_debrid for this trakt user.
trakt.tv could not be reached right now! Please try again later. The script will most likely exit after this message.
it seems this authentification service could not be reached right now. Please try again later.

I've reset Plex_debrid and set it up multiple times. No matter what I do I keep getting the same error</div>

**Comment by emanuelbaltaretu** [comment]
Check issue #666
