### ISSUE TITLE
Error adding Trakt user

### ISSUE THREAD

**Issue by helephant04** [itsToggle/plex_debrid#676]
I'm attempting to add Trakt user lists to my plex-debrid service. When I try to add a list, it says I need at least one user. Every tike I try to add a user, it comes back with 

[trakt] error: (401 unauthorized): trakt api key for user " does not seem to work. Consider re-authorizing plex_debrid for this trakt user. trakt.tv could not be reached right now! Please try again later. The script will most likely exit after this message.

I tried making my own API app on trakt, used the Client ID and Client Secret to replace the two strings in the trakt.py file. That didn't work. I can't find anything online that replicates this issue.

**Comment by syncstimes** [comment]
I'm in the same boat. When I go to:
Options/Settings/Content/Services/Trakt users>add user
I enter my trakt username, but I get the same error as OP above.

That being said, I also don't even know WHERE to add trakt API.

**Comment by Sunstealer1** [comment]
I also have the same issue. It was working fine a few days ago and now it is suddenly throwing this error

**Comment by subsistence** [comment]
Please see https://github.com/itsToggle/plex_debrid/issues/666 - that fixed the issue for me, too.

**Comment by helephant04** [comment]
> Please see #666 - that fixed the issue for me, too.

This worked! Thank you!
