### ISSUE TITLE
plex debrid unable to reach trakt

### ISSUE THREAD

**Issue by 200tylerlee** [itsToggle/plex_debrid#679]
New install, upon initial setup on win 10. plex-debrid cannot reach trakt after giving a name of user. Not sure what the issue is. I've tried it on 2 computers and now a vm. Had it working perfectly before I switched drives and reinstalled windows.

**Comment by igenena** [comment]
There is a fix for the trakt.py code to fix that, search within the github you ll find it and it's so easy to do

**Comment by igenena** [comment]
https://github.com/itsToggle/plex_debrid/issues/666#issuecomment-2024912783
