### ISSUE TITLE
Playback error, requires restart to stream

### ISSUE THREAD

**Issue by varthe** [itsToggle/plex_debrid#681]
When a file is added, it's unable to be played until the server is restarted. 
I get the following playback error:
![image](https://github.com/itsToggle/plex_debrid/assets/59516353/a4043947-29e0-4424-bff8-add15f3d50dc)

Audio/Video codecs also show up as "none".
![image](https://github.com/itsToggle/plex_debrid/assets/59516353/47fdbcf4-314b-4ee2-a063-ed6d2b8964d4)

Then, once I restart the server it works and streams perfectly fine. All notifications (e.g. "HDR is enabled") also show up after restart.
![image](https://github.com/itsToggle/plex_debrid/assets/59516353/c20e7060-60eb-45c0-bd47-30981cf0c1d5)

Analyzing the folders manually through plex doesn't fix it. Is this possibly an issue with the script?

**Comment by varthe** [comment]
Manually analyzing the file just inifnietly loads.

**Comment by mash2k3** [comment]
how do you mount your debrid service?

**Comment by varthe** [comment]
> how do you mount your debrid service?

zurg + rclone

**Comment by mash2k3** [comment]
> > how do you mount your debrid service?
> 
> zurg + rclone

if you are on a linux based system you can try the linux binary instead of docker for zurg

**Comment by varthe** [comment]
Fixed it. I was using the wrong plex token.

If you're using oracle cloud like me:
On **YOUR** machine, not the oracle server, go to [https://plex.tv/devices.xml?X-Plex-Token=](https://plex.tv/devices.xml?X-Plex-Token=). Be sure you're signed into Plex. Don't replace plex.tv with localhost, it has to be plex.tv. Find your oracle server, and copy the token.
