### ISSUE TITLE
Removing media from the "ignored" list doesn't reset scraping attempts

### ISSUE THREAD

**Issue by itsToggle** [itsToggle/plex_debrid#82]
Aside from 6 scraping attempts seeming too little, removing media from the ignored list doesn't reset the scraping attempts.

**Comment by dspdhckr** [comment]
How do I clear ignored media list completely? I have more than 1500 items in it

**Comment by itsToggle** [comment]
Hm, I guess plex_debrid is not really prepared for libraries of your size. I'll add that as a feature as well!
