### ISSUE TITLE
No module named six

### ISSUE THREAD

**Issue by ExtraTorrential** [itsToggle/plex_debrid#85]
Under Setup plex_debrid the dockerized version I run: 1.docker build -t plex_debrid . and it works fine. Then after adding in 2. Run 'docker run -ti plex_debrid' i get no module installed named 'six'.

I have the current version of python and I have installed six as well. Any idea how to get around this? do I need to add six to the container somehow?

**Comment by itsToggle** [comment]
Hey, very sorry for that. I thought six was a standard library. Ive updated the dockerfile, and six should now be installed when you build it.
