### ISSUE TITLE
with jackett I only have results with 1337x 

### ISSUE THREAD

**Issue by gugusman33** [itsToggle/plex_debrid#95]
Hello,
Congratulations on the work done so far!

I have a problem, with jackett I only have results in 1337x with my Yggtorrent or GkTorrent indexer configured in jackett.
![screen1](https://user-images.githubusercontent.com/50148201/187077818-a1b05b70-f2a6-41a9-8d69-a5a620d81193.PNG)

If I remove 1337x and keep Yggtorrent or GkTorrent, Plex_debrid has results but doesn't print results ( doesn't download anything 
, here and in automatic mode)
![screen2](https://user-images.githubusercontent.com/50148201/187077828-95c28b38-200a-438a-99a9-d1886a9adbb6.PNG)

I specify that the research works well on Jackett directly.

Thank you for future feedback

**Comment by itsToggle** [comment]
oh, that's an odd behavior. Could you turn on debug printing and try scraping again? You can find debug printing here: '/Settings/UI Settings/debug printing'

**Comment by gugusman33** [comment]
debug printing has already been activated during my previous test (screen of my first message) ...

**Comment by itsToggle** [comment]
Alright I have an idea what could be going wrong. Do these 2 torrent indexer sites provide torrent files and not magnet links? plex_debrid has a built in torrent to magnet conversion, and Ive always suspected that the hash generation is flawed. I'll check it out!

**Comment by itsToggle** [comment]
Could you try it again with the experimental branch of plex_debrid? You can download the experimental branch here: `https://github.com/itsToggle/plex_debrid/tree/experimental`
or if you use git to clone plex_debrid run: `git clone -b experimental https://github.com/itsToggle/plex_debrid`

**Comment by gugusman33** [comment]
YGGTORRENT only offers downloading torrent files, but GKTORRENTS offers magnets I download the experimental version and I'll get back to you soon! Thanks !

**Comment by itsToggle** [comment]
Alright the first fix wasnt working, I believe ive now fixed it completely. This fix is both present on the main and the experimental branch. Let me know if this latest version works for you.

**Comment by gugusman33** [comment]
Great! everything works perfectly, thank you very much for your reactivity!
